# Université Paul Sabatier
# M1 IAFA - Foundations of Information Retrieval - 2026

Instructors: Lynda Tamine, Karim Radouane and Ahmed Rayane Kebir

Notebook proposed by : Jesús Lovón and José G. Moreno

---

💡 Consider developing auxiliary scripts and functions that will enable you to reuse recurring commands in this practical work (PW) and future ones. This would help you keeping good code practice and make debugging easier.


### Attention❗ About TP grading:
🚨 *Code questions*: Fill in the missing code in the corresponding sections (commented code gets the best marks).

🚨 *Open questions*: Write your textual answer as a comment in the corresponding cells.

🚨 *Keep your outputs*: **Empty outputs (notebook or non-executed cells) correspond to 0 points**.

---

# TP 4. PyTerrier - Neural Re-Ranking

In this PW you will learn to:

 - reclassify documents using neural models such as KNRM, Vanilla BERT, EPIC and monoT5.

## Installations and Setup

> 👉 This PW requires *GPU runtime*

- Installing PyTerrier and  PyTerrier plug-ins  

> We install the PyTerrier plugins [OpenNIR](https://opennir.net/) and [monoT5](https://github.com/terrierteam/pyterrier_t5). You can safely ignore package version errors.

In [ ]:
!pip install -q --upgrade python-terrier
!pip install -q --upgrade git+https://github.com/Georgetown-IR-Lab/OpenNIR
!pip install -q --upgrade git+https://github.com/terrierteam/pyterrier_t5

  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

In [ ]:
# executer pour la cellule 14
!pip install transformers==4.3.3
!pip install tokenizers==0.22.0

Collecting transformers==4.3.3
  Using cached transformers-4.3.3-py3-none-any.whl.metadata (36 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.3.3) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.3.3) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from transformers==4.3.3) (26.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.3.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.3.3) (2.32.4)
Collecting sacremoses (from transformers==4.3.3)
  Using cached sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Collecting tokenizers<0.11,>=0.10.1 (from transformers==4.3.3)
  Using cached tokenizers-0.10.3.tar.gz (212 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.3.3) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.3.3) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.3.3) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.3.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.3.3) (2026.2.25)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from sacremoses->transformers==4.3.3) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from sacremoses->transformers==4.3.3) (1.5.3)
Using cached transformers-4.3.3-py3-none-any.whl (1.9 MB)
Using cached sacremoses-0.1.1-py3-none-any.whl (897 kB)
Building wheels for collected packages: tokenizers
  error: subprocess-exited-with-error

  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tokenizers (pyproject.toml) ... error
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tokenizers)
Requirement already satisfied: tokenizers==0.22.0 in /usr/local/lib/python3.12/dist-packages (0.22.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers==0.22.0) (0.36.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (1.4.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.22.0) (2026.2.25)

We initialize PyTerrier and import libraries as usual

In [ ]:
import os
import pyterrier as pt
from pyterrier.measures import * # allow for natural measure names



# Init PyTerrier
if not pt.started():
    pt.init()

cord19 = pt.datasets.get_dataset('irds:cord19/trec-covid')

/tmp/ipykernel_15343/385787361.py:8: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():
Java started and loaded: pyterrier.java.colab, pyterrier.java, pyterrier.java.24, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_15343/385787361.py:9: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [ ]:
import pandas as pd

You are already familiarized with the indexation for CORD19

In [ ]:
import os
!rm -rf ./terrier_cord19/

pt_index_path = './terrier_cord19'

if not os.path.exists(pt_index_path + "/data.properties"):
    # create the index, using the IterDictIndexer indexer
    indexer = pt.index.IterDictIndexer(pt_index_path, text_attrs=['abstract'], meta=['title','docno'])

    # we give the dataset get_corpus_iter() directly to the indexer
    # while specifying the fields to index and the metadata to record
    # index_ref = indexer.index(cord19.get_corpus_iter(),
    #                           text_attrs=['abstract'])
    indexref = indexer.index(cord19.get_corpus_iter(), )

else:
    # if you already have the index, use it.
    indexref = pt.IndexRef.of(pt_index_path + "/data.properties")

index = pt.IndexFactory.of(indexref)

cord19/trec-covid documents:   0%|          | 0/192509 [00:00<?, ?it/s]

09:08:48.489 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (6iu1dtyl) - further warnings are suppressed
09:09:56.152 [ForkJoinPool-1-worker-1] ERROR org.terrier.structures.indexing.Indexer -- Could not finish MetaIndexBuilder:
java.io.IOException: Key 8lqzfj2e is not unique: 37597,11755
For MetaIndex, to suppress, set metaindex.compressed.reverse.allow.duplicates=true
	at org.terrier.structures.collections.FSOrderedMapFile$MultiFSOMapWriter.mergeTwo(FSOrderedMapFile.java:1374)
	at org.terrier.structures.collections.FSOrderedMapFile$MultiFSOMapWriter.close(FSOrderedMapFile.java:1308)
	at org.terrier.structures.indexing.BaseMetaIndexBuilder.close(BaseMetaIndexBuilder.java:321)
	at org.terrier.structures.indexing.classical.BasicIndexer.indexDocuments(BasicIndexer.java:270)
	at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:388)
	at org.terrier.structures.indexing.Indexer.index(Indexer.java:377)
	at org.terrier.python.ParallelIndexer$3.apply(ParallelIndexer.java:131)
	at org.terrier.python.ParallelIndexer$3.apply(ParallelIndexer.java:120)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at org.terrier.python.ParallelIndexer$4.call(ParallelIndexer.java:140)
	at org.terrier.python.ParallelIndexer$4.call(ParallelIndexer.java:137)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
09:10:01.732 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Indexed 54937 empty documents

# I. Re-Rankers

Let's start exploring some neural re-ranking methods! We can build them from scratch using `onir_pt.reranker`.

OpenNIR's re-ranking model is composed of :
 - `ranker` (for example, `drmm`, `knrm`, or `pacrr`). This defines the neural architecture for ranking.
 - `vocab` (for example, `wordvec_hash`, or `bert`). This defines how the text is encoded by the model. This approach makes it easy to exchange different text representations.

Running this line will take a few minutes, as it downloads and prepares the word vectors.

In [ ]:
import onir_pt

knrm = onir_pt.reranker('knrm', 'wordvec_hash', text_field='abstract')

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
config file not found: config
[2026-03-29 09:10:13,273][WordvecHashVocab][DEBUG] [starting] reading cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p
[2026-03-29 09:10:22,850][WordvecHashVocab][DEBUG] [finished] reading cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p [9.58s]

Let's see how these models work for ranking!

Similar to previous PWs, we load the topics (queries) and qrels.

Then, we create train/dev/test splits for CORD19.

At this stage, we evaluate directly our models (without training).

In [ ]:
tfidf = pt.BatchRetrieve(indexref, wmodel="TF_IDF") % 50
get_text = pt.text.get_text(cord19, 'abstract') #>> pt.apply.title_abstract(lambda r: r['title'] + ' ' + r['abstract'])

/tmp/ipykernel_15343/343583861.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  tfidf = pt.BatchRetrieve(indexref, wmodel="TF_IDF") % 50

In [ ]:
topics = cord19.get_topics(variant='description')
qrels = cord19.get_qrels()

In [ ]:
SEED=42

from sklearn.model_selection import train_test_split

tr_va_topics, test_topics = train_test_split(topics, test_size=15, random_state=SEED)
train_topics, valid_topics =  train_test_split(tr_va_topics, test_size=5, random_state=SEED)


test_qrels = qrels # seulement les annotations des topics en réponse sont utilisés, donc pas de problème si on utilise tout
train_qrels = qrels
valid_qrels = qrels

In [ ]:
# build a sub-pipeline to get the concatenated title and abstract text
pipeline = tfidf >> get_text >> knrm
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> KNRM'],
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10]
)

[2026-03-29 09:10:28,904][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:29,511][onir_pt][DEBUG] [starting] batches

batches: 0it [8ms, ?it/s]

[2026-03-29 09:10:29,529][onir_pt][DEBUG] [finished] batches: [18ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> KNRM ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b664aa91f0> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-29 09:10:33,197][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:33,198][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/188 [5ms<?, ?it/s]

[2026-03-29 09:10:34,256][onir_pt][DEBUG] [finished] batches: [1.06s] [188it] [177.83it/s]

            name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10
0          TFIDF  0.123589  0.595818   0.054568     0.546667
1  TFIDF >> KNRM  0.112743  0.424182   0.042568     0.360000

In [ ]:
tfidf >> get_text >> knrm

[2026-03-29 09:10:34,365][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:34,365][onir_pt][DEBUG] [starting] batches

batches: 0it [6ms, ?it/s]

[2026-03-29 09:10:34,380][onir_pt][DEBUG] [finished] batches: [15ms] [0it] [?it/s]
[2026-03-29 09:10:34,381][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:34,382][onir_pt][DEBUG] [starting] batches

batches: 0it [13ms, ?it/s]

[2026-03-29 09:10:34,403][onir_pt][DEBUG] [finished] batches: [19ms] [0it] [?it/s]
[2026-03-29 09:10:34,405][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:34,405][onir_pt][DEBUG] [starting] batches

batches: 0it [13ms, ?it/s]

[2026-03-29 09:10:34,424][onir_pt][DEBUG] [finished] batches: [19ms] [0it] [?it/s]
[2026-03-29 09:10:34,426][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:34,427][onir_pt][DEBUG] [starting] batches

batches: 0it [12ms, ?it/s]

[2026-03-29 09:10:34,444][onir_pt][DEBUG] [finished] batches: [17ms] [0it] [?it/s]
[2026-03-29 09:10:34,538][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:34,539][onir_pt][DEBUG] [starting] batches

batches: 0it [5ms, ?it/s]

[2026-03-29 09:10:34,553][onir_pt][DEBUG] [finished] batches: [14ms] [0it] [?it/s]

(TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b664aa91f0> >> onir(knrm,wordvec_hash))

This doesn't work very well because the model is not trained; it uses random weights to combine the similarity matrix scores.

# II. Training the re-ranker

You can train re-ranking models in PyTerrier using the `fit` method.

In [ ]:
pipeline.fit(
    train_topics,
    train_qrels,
    valid_topics,
    valid_qrels)

[2026-03-29 09:10:38,799][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:10:38,800][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:38,800][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [5ms<?, ?it/s]

[2026-03-29 09:10:38,951][onir_pt][DEBUG] [finished] batches: [150ms] [63it] [419.13it/s]
[2026-03-29 09:10:39,071][onir_pt][DEBUG] [finished] validation [272ms]
[2026-03-29 09:10:39,072][onir_pt][INFO] pre-validation: 0.0053
[2026-03-29 09:10:39,082][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:39,082][onir_pt][DEBUG] [starting] training
[2026-03-29 09:10:39,083][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:10:39,516][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:39,970][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:41,033][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:42,019][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:42,463][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:43,417][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:44,358][onir_pt][DEBUG] [finished] train pairs: [5.28s] [1024it] [194.12it/s]
[2026-03-29 09:10:44,359][onir_pt][DEBUG] [finished] training [5.28s]
[2026-03-29 09:10:44,359][onir_pt][INFO] training   it=0 loss=0.2451
[2026-03-29 09:10:44,360][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:10:44,360][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:44,362][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [10ms<?, ?it/s]

[2026-03-29 09:10:44,527][onir_pt][DEBUG] [finished] batches: [164ms] [63it] [385.20it/s]
[2026-03-29 09:10:44,669][onir_pt][DEBUG] [finished] validation [310ms]
[2026-03-29 09:10:44,671][onir_pt][INFO] validation it=0 map=0.0058 ndcg=0.0151 P_10=0.0700 <--
[2026-03-29 09:10:44,671][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:44,672][onir_pt][DEBUG] [starting] training
[2026-03-29 09:10:44,672][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:10:44,913][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:44,987][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:46,575][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:47,545][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:47,861][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:48,288][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:48,408][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:48,900][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:49,469][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:49,676][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:49,820][onir_pt][DEBUG] [finished] train pairs: [5.15s] [1024it] [198.92it/s]
[2026-03-29 09:10:49,821][onir_pt][DEBUG] [finished] training [5.15s]
[2026-03-29 09:10:49,822][onir_pt][INFO] training   it=1 loss=0.2213
[2026-03-29 09:10:49,822][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:10:49,822][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:49,822][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [11ms<?, ?it/s]

[2026-03-29 09:10:50,063][onir_pt][DEBUG] [finished] batches: [240ms] [63it] [262.24it/s]
[2026-03-29 09:10:50,269][onir_pt][DEBUG] [finished] validation [447ms]
[2026-03-29 09:10:50,273][onir_pt][INFO] validation it=1 map=0.0059 ndcg=0.0152 P_10=0.0700 <--
[2026-03-29 09:10:50,274][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:50,275][onir_pt][DEBUG] [starting] training
[2026-03-29 09:10:50,275][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [12ms<?, ?it/s]

[2026-03-29 09:10:50,924][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:51,354][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:51,863][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:52,004][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:52,223][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:52,506][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:52,672][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:53,911][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:55,410][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:55,609][onir_pt][DEBUG] [finished] train pairs: [5.33s] [1024it] [191.97it/s]
[2026-03-29 09:10:55,611][onir_pt][DEBUG] [finished] training [5.34s]
[2026-03-29 09:10:55,611][onir_pt][INFO] training   it=2 loss=0.2322
[2026-03-29 09:10:55,611][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:10:55,611][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:55,612][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [12ms<?, ?it/s]

[2026-03-29 09:10:55,781][onir_pt][DEBUG] [finished] batches: [168ms] [63it] [375.48it/s]
[2026-03-29 09:10:55,891][onir_pt][DEBUG] [finished] validation [280ms]
[2026-03-29 09:10:55,892][onir_pt][INFO] validation it=2 map=0.0059 ndcg=0.0152 P_10=0.0700 <--
[2026-03-29 09:10:55,893][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:10:55,893][onir_pt][DEBUG] [starting] training
[2026-03-29 09:10:55,893][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:10:55,928][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:57,749][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:58,163][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:58,572][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:58,880][onir_pt][DEBUG] not enough negs
[2026-03-29 09:10:59,112][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:00,161][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:00,735][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:01,221][onir_pt][DEBUG] [finished] train pairs: [5.33s] [1024it] [192.19it/s]
[2026-03-29 09:11:01,224][onir_pt][DEBUG] [finished] training [5.33s]
[2026-03-29 09:11:01,225][onir_pt][INFO] training   it=3 loss=0.2363
[2026-03-29 09:11:01,225][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:01,225][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:01,225][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [12ms<?, ?it/s]

[2026-03-29 09:11:01,463][onir_pt][DEBUG] [finished] batches: [238ms] [63it] [265.26it/s]
[2026-03-29 09:11:01,667][onir_pt][DEBUG] [finished] validation [442ms]
[2026-03-29 09:11:01,669][onir_pt][INFO] validation it=3 map=0.0061 ndcg=0.0157 P_10=0.0780 <--
[2026-03-29 09:11:01,669][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:01,669][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:01,669][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [7ms<?, ?it/s]

[2026-03-29 09:11:02,020][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:02,418][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:02,596][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:03,717][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:04,357][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:04,923][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:06,799][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:06,956][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:07,430][onir_pt][DEBUG] [finished] train pairs: [5.76s] [1024it] [177.76it/s]
[2026-03-29 09:11:07,432][onir_pt][DEBUG] [finished] training [5.76s]
[2026-03-29 09:11:07,432][onir_pt][INFO] training   it=4 loss=0.2280
[2026-03-29 09:11:07,432][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:07,433][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:07,433][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [9ms<?, ?it/s]

[2026-03-29 09:11:07,610][onir_pt][DEBUG] [finished] batches: [176ms] [63it] [357.33it/s]
[2026-03-29 09:11:07,723][onir_pt][DEBUG] [finished] validation [291ms]
[2026-03-29 09:11:07,724][onir_pt][INFO] validation it=4 map=0.0060 ndcg=0.0154 P_10=0.0720
[2026-03-29 09:11:07,724][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:07,724][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:07,724][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:11:07,840][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:08,279][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:08,763][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:08,811][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:09,020][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:09,660][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:10,049][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:11,961][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:13,000][onir_pt][DEBUG] [finished] train pairs: [5.27s] [1024it] [194.13it/s]
[2026-03-29 09:11:13,001][onir_pt][DEBUG] [finished] training [5.28s]
[2026-03-29 09:11:13,001][onir_pt][INFO] training   it=5 loss=0.2220
[2026-03-29 09:11:13,001][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:13,001][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:13,002][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [8ms<?, ?it/s]

[2026-03-29 09:11:13,175][onir_pt][DEBUG] [finished] batches: [172ms] [63it] [366.27it/s]
[2026-03-29 09:11:13,289][onir_pt][DEBUG] [finished] validation [287ms]
[2026-03-29 09:11:13,289][onir_pt][INFO] validation it=5 map=0.0060 ndcg=0.0154 P_10=0.0740
[2026-03-29 09:11:13,289][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:13,290][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:13,290][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:11:13,789][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:14,213][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:16,392][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:17,148][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:17,760][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:18,367][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:18,719][onir_pt][DEBUG] [finished] train pairs: [5.43s] [1024it] [188.62it/s]
[2026-03-29 09:11:18,721][onir_pt][DEBUG] [finished] training [5.43s]
[2026-03-29 09:11:18,721][onir_pt][INFO] training   it=6 loss=0.2119
[2026-03-29 09:11:18,721][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:18,721][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:18,722][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [16ms<?, ?it/s]

[2026-03-29 09:11:18,999][onir_pt][DEBUG] [finished] batches: [277ms] [63it] [227.35it/s]
[2026-03-29 09:11:19,223][onir_pt][DEBUG] [finished] validation [502ms]
[2026-03-29 09:11:19,224][onir_pt][INFO] validation it=6 map=0.0060 ndcg=0.0155 P_10=0.0720
[2026-03-29 09:11:19,224][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:19,225][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:19,225][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [13ms<?, ?it/s]

[2026-03-29 09:11:19,964][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:20,193][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:20,548][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:20,700][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:20,863][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:22,252][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:22,709][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:23,943][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:24,239][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:24,399][onir_pt][DEBUG] [finished] train pairs: [5.17s] [1024it] [197.89it/s]
[2026-03-29 09:11:24,401][onir_pt][DEBUG] [finished] training [5.18s]
[2026-03-29 09:11:24,402][onir_pt][INFO] training   it=7 loss=0.2151
[2026-03-29 09:11:24,402][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:24,402][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:24,402][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [9ms<?, ?it/s]

[2026-03-29 09:11:24,559][onir_pt][DEBUG] [finished] batches: [156ms] [63it] [403.29it/s]
[2026-03-29 09:11:24,673][onir_pt][DEBUG] [finished] validation [271ms]
[2026-03-29 09:11:24,673][onir_pt][INFO] validation it=7 map=0.0059 ndcg=0.0153 P_10=0.0720
[2026-03-29 09:11:24,673][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:24,674][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:24,674][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:11:24,739][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:25,552][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:25,892][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:25,973][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:26,510][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:27,671][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:28,281][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:28,533][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:28,752][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:29,032][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:29,753][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:30,245][onir_pt][DEBUG] [finished] train pairs: [5.57s] [1024it] [183.79it/s]
[2026-03-29 09:11:30,247][onir_pt][DEBUG] [finished] training [5.57s]
[2026-03-29 09:11:30,248][onir_pt][INFO] training   it=8 loss=0.2287
[2026-03-29 09:11:30,248][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:30,249][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:30,249][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [13ms<?, ?it/s]

[2026-03-29 09:11:30,502][onir_pt][DEBUG] [finished] batches: [252ms] [63it] [249.87it/s]
[2026-03-29 09:11:30,715][onir_pt][DEBUG] [finished] validation [466ms]
[2026-03-29 09:11:30,715][onir_pt][INFO] validation it=8 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-29 09:11:30,716][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:30,716][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:30,716][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [11ms<?, ?it/s]

[2026-03-29 09:11:30,800][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:31,941][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:32,706][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:32,913][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:33,651][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:34,490][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:35,227][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:35,956][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:35,992][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:36,580][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:36,619][onir_pt][DEBUG] [finished] train pairs: [5.90s] [1024it] [173.49it/s]
[2026-03-29 09:11:36,620][onir_pt][DEBUG] [finished] training [5.90s]
[2026-03-29 09:11:36,620][onir_pt][INFO] training   it=9 loss=0.2266
[2026-03-29 09:11:36,621][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:36,621][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:36,621][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [9ms<?, ?it/s]

[2026-03-29 09:11:36,793][onir_pt][DEBUG] [finished] batches: [172ms] [63it] [367.17it/s]
[2026-03-29 09:11:36,908][onir_pt][DEBUG] [finished] validation [287ms]
[2026-03-29 09:11:36,908][onir_pt][INFO] validation it=9 map=0.0060 ndcg=0.0153 P_10=0.0680
[2026-03-29 09:11:36,908][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:36,908][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:36,909][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:11:37,758][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:37,924][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:38,490][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:38,875][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:38,970][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:40,144][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:40,223][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:41,032][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:41,659][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:42,249][onir_pt][DEBUG] [finished] train pairs: [5.34s] [1024it] [191.76it/s]
[2026-03-29 09:11:42,250][onir_pt][DEBUG] [finished] training [5.34s]
[2026-03-29 09:11:42,251][onir_pt][INFO] training   it=10 loss=0.2252
[2026-03-29 09:11:42,251][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:42,251][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:42,252][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [8ms<?, ?it/s]

[2026-03-29 09:11:42,421][onir_pt][DEBUG] [finished] batches: [168ms] [63it] [374.06it/s]
[2026-03-29 09:11:42,558][onir_pt][DEBUG] [finished] validation [307ms]
[2026-03-29 09:11:42,559][onir_pt][INFO] validation it=10 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-29 09:11:42,559][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:42,559][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:42,559][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:11:43,367][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:43,473][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:43,890][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:44,567][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:45,622][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:46,776][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:47,506][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:48,611][onir_pt][DEBUG] [finished] train pairs: [6.05s] [1024it] [169.20it/s]
[2026-03-29 09:11:48,614][onir_pt][DEBUG] [finished] training [6.05s]
[2026-03-29 09:11:48,616][onir_pt][INFO] training   it=11 loss=0.2158
[2026-03-29 09:11:48,616][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:48,617][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:48,617][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [12ms<?, ?it/s]

[2026-03-29 09:11:48,891][onir_pt][DEBUG] [finished] batches: [274ms] [63it] [230.16it/s]
[2026-03-29 09:11:49,015][onir_pt][DEBUG] [finished] validation [399ms]
[2026-03-29 09:11:49,015][onir_pt][INFO] validation it=11 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-29 09:11:49,015][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:49,016][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:49,016][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:11:49,422][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:49,654][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:51,644][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:52,204][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:52,380][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:52,734][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:53,237][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:53,899][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:54,354][onir_pt][DEBUG] [finished] train pairs: [5.34s] [1024it] [191.83it/s]
[2026-03-29 09:11:54,355][onir_pt][DEBUG] [finished] training [5.34s]
[2026-03-29 09:11:54,357][onir_pt][INFO] training   it=12 loss=0.2179
[2026-03-29 09:11:54,357][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:11:54,357][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:54,358][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [8ms<?, ?it/s]

[2026-03-29 09:11:54,551][onir_pt][DEBUG] [finished] batches: [194ms] [63it] [325.53it/s]
[2026-03-29 09:11:54,663][onir_pt][DEBUG] [finished] validation [307ms]
[2026-03-29 09:11:54,664][onir_pt][INFO] validation it=12 map=0.0059 ndcg=0.0153 P_10=0.0700
[2026-03-29 09:11:54,664][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:11:54,665][onir_pt][DEBUG] [starting] training
[2026-03-29 09:11:54,665][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:11:55,016][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:55,100][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:56,131][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:56,402][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:58,319][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:58,701][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:58,826][onir_pt][DEBUG] not enough negs
[2026-03-29 09:11:59,410][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:00,113][onir_pt][DEBUG] [finished] train pairs: [5.45s] [1024it] [187.94it/s]
[2026-03-29 09:12:00,115][onir_pt][DEBUG] [finished] training [5.45s]
[2026-03-29 09:12:00,115][onir_pt][INFO] training   it=13 loss=0.2402
[2026-03-29 09:12:00,116][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:00,116][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:00,116][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [8ms<?, ?it/s]

[2026-03-29 09:12:00,322][onir_pt][DEBUG] [finished] batches: [205ms] [63it] [306.75it/s]
[2026-03-29 09:12:00,522][onir_pt][DEBUG] [finished] validation [407ms]
[2026-03-29 09:12:00,523][onir_pt][INFO] validation it=13 map=0.0053 ndcg=0.0142 P_10=0.0500
[2026-03-29 09:12:00,523][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:00,524][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:00,524][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [8ms<?, ?it/s]

[2026-03-29 09:12:00,963][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:01,525][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:02,645][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:04,223][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:04,465][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:06,053][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:06,118][onir_pt][DEBUG] [finished] train pairs: [5.59s] [1024it] [183.06it/s]
[2026-03-29 09:12:06,119][onir_pt][DEBUG] [finished] training [5.60s]
[2026-03-29 09:12:06,122][onir_pt][INFO] training   it=14 loss=0.2255
[2026-03-29 09:12:06,122][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:06,122][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:06,123][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [10ms<?, ?it/s]

[2026-03-29 09:12:06,283][onir_pt][DEBUG] [finished] batches: [160ms] [63it] [393.22it/s]
[2026-03-29 09:12:06,416][onir_pt][DEBUG] [finished] validation [294ms]
[2026-03-29 09:12:06,417][onir_pt][INFO] validation it=14 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-29 09:12:06,417][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:06,417][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:06,417][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:12:06,454][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:06,763][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:07,619][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:07,900][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:08,168][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:09,611][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:10,707][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:10,853][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:11,101][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:11,453][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:11,749][onir_pt][DEBUG] [finished] train pairs: [5.33s] [1024it] [192.05it/s]
[2026-03-29 09:12:11,751][onir_pt][DEBUG] [finished] training [5.33s]
[2026-03-29 09:12:11,753][onir_pt][INFO] training   it=15 loss=0.2227
[2026-03-29 09:12:11,753][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:11,754][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:11,754][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [14ms<?, ?it/s]

[2026-03-29 09:12:11,930][onir_pt][DEBUG] [finished] batches: [176ms] [63it] [358.88it/s]
[2026-03-29 09:12:12,047][onir_pt][DEBUG] [finished] validation [294ms]
[2026-03-29 09:12:12,048][onir_pt][INFO] validation it=15 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-29 09:12:12,048][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:12,049][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:12,049][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:12:12,443][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:12,912][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:12,999][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:13,131][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:13,327][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:13,658][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:16,321][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:16,410][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:17,405][onir_pt][DEBUG] [finished] train pairs: [5.36s] [1024it] [191.20it/s]
[2026-03-29 09:12:17,408][onir_pt][DEBUG] [finished] training [5.36s]
[2026-03-29 09:12:17,408][onir_pt][INFO] training   it=16 loss=0.2296
[2026-03-29 09:12:17,408][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:17,408][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:17,408][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [10ms<?, ?it/s]

[2026-03-29 09:12:17,668][onir_pt][DEBUG] [finished] batches: [260ms] [63it] [242.77it/s]
[2026-03-29 09:12:17,896][onir_pt][DEBUG] [finished] validation [487ms]
[2026-03-29 09:12:17,897][onir_pt][INFO] validation it=16 map=0.0060 ndcg=0.0154 P_10=0.0700
[2026-03-29 09:12:17,897][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:17,897][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:17,897][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [11ms<?, ?it/s]

[2026-03-29 09:12:18,137][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:19,175][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:19,427][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:20,041][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:20,172][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:20,837][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:20,994][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:21,982][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:22,236][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:22,326][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:22,846][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:23,575][onir_pt][DEBUG] [finished] train pairs: [5.68s] [1024it] [180.37it/s]
[2026-03-29 09:12:23,576][onir_pt][DEBUG] [finished] training [5.68s]
[2026-03-29 09:12:23,577][onir_pt][INFO] training   it=17 loss=0.2347
[2026-03-29 09:12:23,577][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:23,577][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:23,580][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [10ms<?, ?it/s]

[2026-03-29 09:12:23,759][onir_pt][DEBUG] [finished] batches: [178ms] [63it] [352.98it/s]
[2026-03-29 09:12:23,875][onir_pt][DEBUG] [finished] validation [298ms]
[2026-03-29 09:12:23,875][onir_pt][INFO] validation it=17 map=0.0061 ndcg=0.0155 P_10=0.0720
[2026-03-29 09:12:23,876][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:23,876][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:23,876][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:12:23,931][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:24,026][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:24,435][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:24,676][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:25,223][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:26,190][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:26,588][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:27,267][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:28,830][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:29,297][onir_pt][DEBUG] [finished] train pairs: [5.42s] [1024it] [188.91it/s]
[2026-03-29 09:12:29,299][onir_pt][DEBUG] [finished] training [5.42s]
[2026-03-29 09:12:29,299][onir_pt][INFO] training   it=18 loss=0.2179
[2026-03-29 09:12:29,300][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:29,300][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:29,301][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [11ms<?, ?it/s]

[2026-03-29 09:12:29,527][onir_pt][DEBUG] [finished] batches: [225ms] [63it] [279.91it/s]
[2026-03-29 09:12:29,722][onir_pt][DEBUG] [finished] validation [423ms]
[2026-03-29 09:12:29,723][onir_pt][INFO] validation it=18 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-29 09:12:29,723][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:29,723][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:29,723][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [10ms<?, ?it/s]

[2026-03-29 09:12:30,411][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:30,653][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:32,152][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:33,391][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:33,609][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:33,853][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:34,139][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:35,360][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:35,409][onir_pt][DEBUG] [finished] train pairs: [5.69s] [1024it] [180.10it/s]
[2026-03-29 09:12:35,414][onir_pt][DEBUG] [finished] training [5.69s]
[2026-03-29 09:12:35,414][onir_pt][INFO] training   it=19 loss=0.2325
[2026-03-29 09:12:35,414][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:35,414][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:35,415][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [14ms<?, ?it/s]

[2026-03-29 09:12:35,642][onir_pt][DEBUG] [finished] batches: [227ms] [63it] [277.65it/s]
[2026-03-29 09:12:35,842][onir_pt][DEBUG] [finished] validation [428ms]
[2026-03-29 09:12:35,843][onir_pt][INFO] validation it=19 map=0.0060 ndcg=0.0154 P_10=0.0700
[2026-03-29 09:12:35,843][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:35,843][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:35,843][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:12:36,276][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:36,340][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:36,494][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:36,733][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:38,365][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:38,945][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:39,389][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:40,175][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:41,061][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:41,248][onir_pt][DEBUG] [finished] train pairs: [5.40s] [1024it] [189.47it/s]
[2026-03-29 09:12:41,250][onir_pt][DEBUG] [finished] training [5.41s]
[2026-03-29 09:12:41,250][onir_pt][INFO] training   it=20 loss=0.2076
[2026-03-29 09:12:41,251][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:41,251][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:41,251][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [12ms<?, ?it/s]

[2026-03-29 09:12:41,426][onir_pt][DEBUG] [finished] batches: [174ms] [63it] [362.28it/s]
[2026-03-29 09:12:41,542][onir_pt][DEBUG] [finished] validation [291ms]
[2026-03-29 09:12:41,542][onir_pt][INFO] validation it=20 map=0.0060 ndcg=0.0154 P_10=0.0700
[2026-03-29 09:12:41,542][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:41,542][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:41,543][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:12:41,816][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:42,357][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:42,526][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:42,878][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:44,254][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:44,684][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:45,530][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:45,900][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:46,170][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:47,317][onir_pt][DEBUG] [finished] train pairs: [5.77s] [1024it] [177.33it/s]
[2026-03-29 09:12:47,321][onir_pt][DEBUG] [finished] training [5.78s]
[2026-03-29 09:12:47,322][onir_pt][INFO] training   it=21 loss=0.2283
[2026-03-29 09:12:47,322][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:47,322][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:47,322][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [11ms<?, ?it/s]

[2026-03-29 09:12:47,546][onir_pt][DEBUG] [finished] batches: [223ms] [63it] [282.66it/s]
[2026-03-29 09:12:47,749][onir_pt][DEBUG] [finished] validation [427ms]
[2026-03-29 09:12:47,750][onir_pt][INFO] validation it=21 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-29 09:12:47,751][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:47,751][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:47,751][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [9ms<?, ?it/s]

[2026-03-29 09:12:47,963][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:48,721][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:49,113][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:49,751][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:50,811][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:51,616][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:52,038][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:52,371][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:52,375][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:53,557][onir_pt][DEBUG] [finished] train pairs: [5.80s] [1024it] [176.40it/s]
[2026-03-29 09:12:53,558][onir_pt][DEBUG] [finished] training [5.81s]
[2026-03-29 09:12:53,559][onir_pt][INFO] training   it=22 loss=0.2240
[2026-03-29 09:12:53,559][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:53,559][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:53,560][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [9ms<?, ?it/s]

[2026-03-29 09:12:53,744][onir_pt][DEBUG] [finished] batches: [184ms] [63it] [342.09it/s]
[2026-03-29 09:12:53,875][onir_pt][DEBUG] [finished] validation [316ms]
[2026-03-29 09:12:53,876][onir_pt][INFO] validation it=22 map=0.0060 ndcg=0.0154 P_10=0.0700
[2026-03-29 09:12:53,876][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:53,877][onir_pt][DEBUG] [starting] training
[2026-03-29 09:12:53,877][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [7ms<?, ?it/s]

[2026-03-29 09:12:54,430][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:54,769][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:55,092][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:55,821][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:56,324][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:58,620][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:59,200][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:59,486][onir_pt][DEBUG] not enough negs
[2026-03-29 09:12:59,496][onir_pt][DEBUG] [finished] train pairs: [5.62s] [1024it] [182.25it/s]
[2026-03-29 09:12:59,497][onir_pt][DEBUG] [finished] training [5.62s]
[2026-03-29 09:12:59,497][onir_pt][INFO] training   it=23 loss=0.2234
[2026-03-29 09:12:59,498][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:12:59,498][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:59,499][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/63 [11ms<?, ?it/s]

[2026-03-29 09:12:59,706][onir_pt][DEBUG] [finished] batches: [206ms] [63it] [305.50it/s]
[2026-03-29 09:12:59,913][onir_pt][DEBUG] [finished] validation [416ms]
[2026-03-29 09:12:59,914][onir_pt][INFO] validation it=23 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-29 09:12:59,914][onir_pt][INFO] early stopping; model reverting back to it=3

In [ ]:
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> KNRM (trained)'],
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10]
)

[2026-03-29 09:12:59,968][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:12:59,969][onir_pt][DEBUG] [starting] batches

batches: 0it [19ms, ?it/s]

[2026-03-29 09:12:59,994][onir_pt][DEBUG] [finished] batches: [25ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> KNRM (trained) ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b664aa91f0> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-29 09:13:01,875][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:13:01,876][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/188 [11ms<?, ?it/s]

[2026-03-29 09:13:02,407][onir_pt][DEBUG] [finished] batches: [531ms] [188it] [353.76it/s]

                      name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10
0                    TFIDF  0.123589  0.595818   0.054568     0.546667
1  TFIDF >> KNRM (trained)  0.121854  0.521672   0.052443     0.453333

#### Question ✍
1. The result is higher, but still not as good as TFIDF. Propose a hypothesis on the problem.

The results show that the neural re-ranker (KNRM) is actually performing slightly worse than the simple keyword-based TF-IDF across all metrics (AP, P@10, nDCG).

We have:

|  name | nDGC  | nDGC@10  | AP(rel=2)  | P(rel=2)@10 |
|---|---|---|---|---|
| TFIDF | 0.123  | 0.595 | 0.054 | 0.546  |
|  TFIDS>>KNRM(trained) | 0.121 | 0.521  | 0.052 | 0.453 |
|  TFIDS>>KNRM  | 0.112  |  0.424 | 0.042  | 0.360  |

We can pretty clearly see that the result is higher but not quite as high as the TFIDF result.

This can be explained by the following reasons:

- Since the KNRM model is kernel based it relies on pre-training. the covid19 dataset being pretuy domain specific. It doesn't give very optimal results.
- Following the domain specific spectrum. We can also say that since TF-IDF matches the exact vocabulary and Kernel Pooling doesn't. This can be a factor to the poor performance of our pipeline.

# III. Vanilla BERT

Contextualized language models, such as [BERT](https://arxiv.org/abs/1810.04805), are much more powerful neural models that have proven effective for classification.

We will try to use a “vanilla” (or “mono”) version of the BERT model. The BERT model is pre-trained for language modeling and next-sentence prediction.

In [ ]:
del knrm # clear out memory from KNRM
vbert = onir_pt.reranker('vanilla_transformer', 'bert', text_field='abstract', vocab_config={'train': True})

Let's see how this model performs on the TREC CORD19 collection.

In [ ]:
pipeline = tfidf % 50 >> get_text >> vbert
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> VBERT'],
    baseline=0,
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10]
)

[2026-03-29 09:13:09,063][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:13:09,209][onir_pt][DEBUG] [starting] batches

batches: 0it [6ms, ?it/s]

[2026-03-29 09:13:09,221][onir_pt][DEBUG] [finished] batches: [12ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> VBERT ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b664aa91f0> >> onir(vanilla_transformer,bert)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-29 09:13:10,677][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:13:10,680][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/188 [5ms<?, ?it/s]

[2026-03-29 09:13:37,614][onir_pt][DEBUG] [finished] batches: [26.93s] [188it] [ 6.98it/s]

,name,nDCG,nDCG@10,AP(rel=2),P(rel=2)@10,nDCG +,nDCG -,nDCG p-value,nDCG@10 +,nDCG@10 -,nDCG@10 p-value,AP(rel=2) +,AP(rel=2) -,AP(rel=2) p-value,P(rel=2)@10 +,P(rel=2)@10 -,P(rel=2)@10 p-value
0,TFIDF,0.123589,0.595818,0.054568,0.546667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TFIDF >> VBERT,0.121068,0.526283,0.051388,0.466667,4.0,11.0,0.537761,6.0,9.0,0.200217,4.0,11.0,0.249944,5.0,8.0,0.110861

Added by Henry JIMENEZ:
Here we can't really say that VBERT model is outperforming TFIDF. All this complexity added proves unefective. Maybe SLM's could be more effective ?
This reminds me. Maybe a TER subject could talk about how can SLM's can level or even outperform LLM in domain specific tasks ?

As we can see, although the model is pre-trained, it doesn't perform very well. This is because it is not tuned for the relevance ranking task.

However, we can train the model for ranking (as described above for KNRM).

# IV. monoT5

The [monoT5 model](https://arxiv.org/abs/2003.06713) evaluates documents using a causal language model. Let's see how this approach works on TREC COVID.

The `MonoT5ReRanker` class in `pyterrier_t5` automatically loads a version of the monoT5 workbook, which is trained on the MS MARCO passage dataset.

In [ ]:
from pyterrier_t5 import MonoT5ReRanker
monoT5 = MonoT5ReRanker(text_field='abstract')

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [ ]:
tfidf >> get_text >> monoT5

(TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b664aa91f0> >> MonoT5(castorini/monot5-base-msmarco))

In [ ]:
pipeline = (tfidf >> get_text >> monoT5)
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> T5'],
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10, "mrt"]
)

monoT5:   0%|          | 0/188 [6ms<?, ?batches/s]

          name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10           mrt
0        TFIDF  0.123589  0.595818   0.054568     0.546667    578.152801
1  TFIDF >> T5  0.128997  0.700101   0.060670     0.606667  31634.993203

Added by Henry JIMENEZ:

Here we can see that the result outperforms TF-IDF by an outstanding 10 %. In all metrics and by an unfathomable amount for mrt. monoT5 proves to be the superior model. Not as much as an SLM though. Maybe a study with specialised benchmarks in a TER could prove this statement ?

As expected, the results are much better in terms of NDCG@10 (0.5958 vs. 0.6855).

# Application

#### Question ✍

Simlar to the previous PW, use the models implemented for cord19 in a question-answer task.

In this context, queries are questions and documents are documents that might contain the answer.

Note that you'll need to redo the indexing as well as the other steps studied in this tutorial. You can download the dataset using the lines of code below.

In [ ]:
import re
from pandas import DataFrame

fiqa = {}
fiqa['train'] = pt.datasets.get_dataset('irds:beir/fiqa/train')
fiqa['valid'] = pt.datasets.get_dataset('irds:beir/fiqa/dev')
fiqa['test'] = pt.datasets.get_dataset('irds:beir/fiqa/test')

def clean_query(topics: DataFrame):
    topics['query'] = topics['query'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))



test_topics = fiqa['test'].get_topics(variant='text')
clean_query(test_topics)
test_qrels = fiqa['test'].get_qrels()

train_topics = fiqa['train'].get_topics(variant='text')
clean_query( train_topics )
train_qrels = fiqa['train'].get_qrels()

valid_topics = fiqa['valid'].get_topics(variant='text')
clean_query( valid_topics )
valid_qrels = fiqa['valid'].get_qrels()

#Dataset pour créer l'index :
dataset_fiqa = pt.datasets.get_dataset('irds:beir/fiqa')

In [ ]:
#### Indexation dataset fiqa

import os
!rm -rf ./terrier_fiqa/

pt_index_path = './terrier_fiqa'

if not os.path.exists(pt_index_path + "/data.properties"):
    # create the index, using the IterDictIndexer indexer
    indexer = pt.index.IterDictIndexer(pt_index_path, text_attrs=['text'], meta=['docno'], fields=True)

    # we give the dataset get_corpus_iter() directly to the indexer
    # while specifying the fields to index and the metadata to record
    # index_ref = indexer.index(cord19.get_corpus_iter(),
    #                           text_attrs=['abstract'])
    indexref_piqa = indexer.index(dataset_fiqa.get_corpus_iter(), )

else:
    # if you already have the index, use it.
    indexref_piqa = pt.IndexRef.of(pt_index_path + "/data.properties")

index_piqa = pt.IndexFactory.of(indexref)

beir/fiqa documents:   0%|          | 0/57638 [6ms<?, ?it/s]

09:14:28.824 [ForkJoinPool-2-worker-1] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (7915) - further warnings are suppressed
09:14:44.554 [ForkJoinPool-2-worker-1] WARN org.terrier.structures.indexing.Indexer -- Indexed 39 empty documents

In [ ]:
tfidf = pt.BatchRetrieve(indexref_piqa, wmodel="TF_IDF") % 50
get_text = pt.text.get_text(dataset_fiqa, 'text') #>> pt.apply.title_abstract(lambda r: r['title'] + ' ' + r['abstract'])

/tmp/ipykernel_15343/344516202.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  tfidf = pt.BatchRetrieve(indexref_piqa, wmodel="TF_IDF") % 50

In [ ]:
knrm = onir_pt.reranker('knrm', 'wordvec_hash', text_field='text')

[2026-03-29 09:14:44,672][WordvecHashVocab][DEBUG] [starting] reading cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p
[2026-03-29 09:14:54,400][WordvecHashVocab][DEBUG] [finished] reading cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p [9.73s]

In [ ]:
# build a sub-pipeline to get the concatenated title and abstract text
# non trained KNRM
pipeline = tfidf >> get_text >> knrm
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    test_qrels,
    names=['TFIDF', 'TFIDF >> KNRM'],
    # On met nos données à rel=1 puisqu'il n'existe pas un niveau de pertinence égal à 2 dans qrels.
    eval_metrics=[AP(rel=1), nDCG, nDCG@10, P(rel=1)@10]
)

[2026-03-29 09:15:01,037][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:15:01,382][onir_pt][DEBUG] [starting] batches

batches: 0it [29ms, ?it/s]

[2026-03-29 09:15:01,420][onir_pt][DEBUG] [finished] batches: [37ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> KNRM ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b66662c770> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-29 09:15:37,798][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:15:37,799][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/8100 [6ms<?, ?it/s]

[2026-03-29 09:15:56,341][onir_pt][DEBUG] [finished] batches: [18.54s] [8100it] [436.84it/s]

            name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10
0          TFIDF  0.289927  0.242948        0.0          0.0
1  TFIDF >> KNRM  0.142833  0.052018        0.0          0.0

In [ ]:
pipeline.fit(
    train_topics,
    train_qrels,
    valid_topics,
    valid_qrels)

[2026-03-29 09:22:56,542][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:22:56,543][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:22:56,543][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [6ms<?, ?it/s]

[2026-03-29 09:23:11,236][onir_pt][DEBUG] [finished] batches: [14.69s] [6250it] [425.40it/s]
[2026-03-29 09:23:11,321][onir_pt][DEBUG] [finished] validation [14.78s]
[2026-03-29 09:23:11,321][onir_pt][INFO] pre-validation: 0.0410
[2026-03-29 09:23:11,334][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:23:11,334][onir_pt][DEBUG] [starting] training
[2026-03-29 09:23:11,334][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:23:17,666][onir_pt][DEBUG] [finished] train pairs: [6.33s] [1024it] [161.73it/s]
[2026-03-29 09:23:17,667][onir_pt][DEBUG] [finished] training [6.33s]
[2026-03-29 09:23:17,668][onir_pt][INFO] training   it=0 loss=0.2479
[2026-03-29 09:23:17,668][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:23:17,668][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:23:17,669][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [6ms<?, ?it/s]

[2026-03-29 09:23:31,463][onir_pt][DEBUG] [finished] batches: [13.79s] [6250it] [453.09it/s]
[2026-03-29 09:23:31,550][onir_pt][DEBUG] [finished] validation [13.88s]
[2026-03-29 09:23:31,552][onir_pt][INFO] validation it=0 map=0.0505 ndcg=0.1498 P_10=0.0244 <--
[2026-03-29 09:23:31,552][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:23:31,552][onir_pt][DEBUG] [starting] training
[2026-03-29 09:23:31,553][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:23:41,265][onir_pt][DEBUG] [finished] train pairs: [9.71s] [1024it] [105.44it/s]
[2026-03-29 09:23:41,268][onir_pt][DEBUG] [finished] training [9.72s]
[2026-03-29 09:23:41,268][onir_pt][INFO] training   it=1 loss=0.2451
[2026-03-29 09:23:41,268][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:23:41,268][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:23:41,269][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [28ms<?, ?it/s]

[2026-03-29 09:23:56,434][onir_pt][DEBUG] [finished] batches: [15.16s] [6250it] [412.14it/s]
[2026-03-29 09:23:56,522][onir_pt][DEBUG] [finished] validation [15.25s]
[2026-03-29 09:23:56,524][onir_pt][INFO] validation it=1 map=0.0528 ndcg=0.1532 P_10=0.0240 <--
[2026-03-29 09:23:56,524][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:23:56,525][onir_pt][DEBUG] [starting] training
[2026-03-29 09:23:56,525][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:24:01,765][onir_pt][DEBUG] [finished] train pairs: [5.24s] [1024it] [195.42it/s]
[2026-03-29 09:24:01,767][onir_pt][DEBUG] [finished] training [5.24s]
[2026-03-29 09:24:01,770][onir_pt][INFO] training   it=2 loss=0.2313
[2026-03-29 09:24:01,770][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:24:01,770][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:24:01,771][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:24:18,793][onir_pt][DEBUG] [finished] batches: [17.02s] [6250it] [367.18it/s]
[2026-03-29 09:24:18,927][onir_pt][DEBUG] [finished] validation [17.16s]
[2026-03-29 09:24:18,929][onir_pt][INFO] validation it=2 map=0.0530 ndcg=0.1533 P_10=0.0238 <--
[2026-03-29 09:24:18,929][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:24:18,929][onir_pt][DEBUG] [starting] training
[2026-03-29 09:24:18,930][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [11ms<?, ?it/s]

[2026-03-29 09:24:26,262][onir_pt][DEBUG] [finished] train pairs: [7.33s] [1024it] [139.67it/s]
[2026-03-29 09:24:26,263][onir_pt][DEBUG] [finished] training [7.33s]
[2026-03-29 09:24:26,263][onir_pt][INFO] training   it=3 loss=0.2372
[2026-03-29 09:24:26,263][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:24:26,263][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:24:26,264][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:24:44,834][onir_pt][DEBUG] [finished] batches: [18.57s] [6250it] [336.58it/s]
[2026-03-29 09:24:45,204][onir_pt][DEBUG] [finished] validation [18.94s]
[2026-03-29 09:24:45,207][onir_pt][INFO] validation it=3 map=0.0530 ndcg=0.1533 P_10=0.0242
[2026-03-29 09:24:45,207][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:24:45,208][onir_pt][DEBUG] [starting] training
[2026-03-29 09:24:45,208][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [35ms<?, ?it/s]

[2026-03-29 09:24:55,374][onir_pt][DEBUG] [finished] train pairs: [10.17s] [1024it] [100.73it/s]
[2026-03-29 09:24:55,378][onir_pt][DEBUG] [finished] training [10.17s]
[2026-03-29 09:24:55,378][onir_pt][INFO] training   it=4 loss=0.2331
[2026-03-29 09:24:55,378][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:24:55,379][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:24:55,381][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [28ms<?, ?it/s]

[2026-03-29 09:25:19,374][onir_pt][DEBUG] [finished] batches: [23.99s] [6250it] [260.50it/s]
[2026-03-29 09:25:19,530][onir_pt][DEBUG] [finished] validation [24.15s]
[2026-03-29 09:25:19,533][onir_pt][INFO] validation it=4 map=0.0544 ndcg=0.1546 P_10=0.0240 <--
[2026-03-29 09:25:19,533][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:25:19,533][onir_pt][DEBUG] [starting] training
[2026-03-29 09:25:19,534][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [31ms<?, ?it/s]

[2026-03-29 09:25:28,074][onir_pt][DEBUG] [finished] train pairs: [8.54s] [1024it] [119.91it/s]
[2026-03-29 09:25:28,077][onir_pt][DEBUG] [finished] training [8.54s]
[2026-03-29 09:25:28,078][onir_pt][INFO] training   it=5 loss=0.2316
[2026-03-29 09:25:28,082][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:25:28,082][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:25:28,083][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [22ms<?, ?it/s]

[2026-03-29 09:25:43,085][onir_pt][DEBUG] [finished] batches: [15.00s] [6250it] [416.66it/s]
[2026-03-29 09:25:43,168][onir_pt][DEBUG] [finished] validation [15.09s]
[2026-03-29 09:25:43,168][onir_pt][INFO] validation it=5 map=0.0539 ndcg=0.1538 P_10=0.0238
[2026-03-29 09:25:43,168][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:25:43,169][onir_pt][DEBUG] [starting] training
[2026-03-29 09:25:43,169][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:25:48,338][onir_pt][DEBUG] [finished] train pairs: [5.17s] [1024it] [198.10it/s]
[2026-03-29 09:25:48,340][onir_pt][DEBUG] [finished] training [5.17s]
[2026-03-29 09:25:48,340][onir_pt][INFO] training   it=6 loss=0.2202
[2026-03-29 09:25:48,340][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:25:48,340][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:25:48,341][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:26:02,089][onir_pt][DEBUG] [finished] batches: [13.75s] [6250it] [454.66it/s]
[2026-03-29 09:26:02,187][onir_pt][DEBUG] [finished] validation [13.85s]
[2026-03-29 09:26:02,188][onir_pt][INFO] validation it=6 map=0.0544 ndcg=0.1544 P_10=0.0244
[2026-03-29 09:26:02,188][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:26:02,188][onir_pt][DEBUG] [starting] training
[2026-03-29 09:26:02,188][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:26:08,235][onir_pt][DEBUG] [finished] train pairs: [6.05s] [1024it] [169.34it/s]
[2026-03-29 09:26:08,237][onir_pt][DEBUG] [finished] training [6.05s]
[2026-03-29 09:26:08,237][onir_pt][INFO] training   it=7 loss=0.2233
[2026-03-29 09:26:08,238][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:26:08,238][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:26:08,238][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:26:22,070][onir_pt][DEBUG] [finished] batches: [13.83s] [6250it] [451.87it/s]
[2026-03-29 09:26:22,151][onir_pt][DEBUG] [finished] validation [13.91s]
[2026-03-29 09:26:22,153][onir_pt][INFO] validation it=7 map=0.0546 ndcg=0.1545 P_10=0.0240 <--
[2026-03-29 09:26:22,153][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:26:22,154][onir_pt][DEBUG] [starting] training
[2026-03-29 09:26:22,154][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:26:27,515][onir_pt][DEBUG] [finished] train pairs: [5.36s] [1024it] [191.02it/s]
[2026-03-29 09:26:27,517][onir_pt][DEBUG] [finished] training [5.36s]
[2026-03-29 09:26:27,518][onir_pt][INFO] training   it=8 loss=0.2340
[2026-03-29 09:26:27,518][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:26:27,518][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:26:27,519][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:26:41,350][onir_pt][DEBUG] [finished] batches: [13.83s] [6250it] [451.90it/s]
[2026-03-29 09:26:41,433][onir_pt][DEBUG] [finished] validation [13.91s]
[2026-03-29 09:26:41,435][onir_pt][INFO] validation it=8 map=0.0560 ndcg=0.1560 P_10=0.0248 <--
[2026-03-29 09:26:41,435][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:26:41,435][onir_pt][DEBUG] [starting] training
[2026-03-29 09:26:41,435][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:26:47,829][onir_pt][DEBUG] [finished] train pairs: [6.39s] [1024it] [160.16it/s]
[2026-03-29 09:26:47,830][onir_pt][DEBUG] [finished] training [6.40s]
[2026-03-29 09:26:47,831][onir_pt][INFO] training   it=9 loss=0.2344
[2026-03-29 09:26:47,831][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:26:47,831][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:26:47,833][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:27:01,784][onir_pt][DEBUG] [finished] batches: [13.95s] [6250it] [448.00it/s]
[2026-03-29 09:27:01,869][onir_pt][DEBUG] [finished] validation [14.04s]
[2026-03-29 09:27:01,869][onir_pt][INFO] validation it=9 map=0.0545 ndcg=0.1546 P_10=0.0244
[2026-03-29 09:27:01,869][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:27:01,870][onir_pt][DEBUG] [starting] training
[2026-03-29 09:27:01,870][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:27:07,359][onir_pt][DEBUG] [finished] train pairs: [5.49s] [1024it] [186.56it/s]
[2026-03-29 09:27:07,360][onir_pt][DEBUG] [finished] training [5.49s]
[2026-03-29 09:27:07,361][onir_pt][INFO] training   it=10 loss=0.2353
[2026-03-29 09:27:07,361][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:27:07,361][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:27:07,364][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [6ms<?, ?it/s]

[2026-03-29 09:27:22,986][onir_pt][DEBUG] [finished] batches: [15.62s] [6250it] [400.09it/s]
[2026-03-29 09:27:23,135][onir_pt][DEBUG] [finished] validation [15.77s]
[2026-03-29 09:27:23,138][onir_pt][INFO] validation it=10 map=0.0575 ndcg=0.1570 P_10=0.0250 <--
[2026-03-29 09:27:23,138][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:27:23,140][onir_pt][DEBUG] [starting] training
[2026-03-29 09:27:23,140][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [10ms<?, ?it/s]

[2026-03-29 09:27:28,782][onir_pt][DEBUG] [finished] train pairs: [5.64s] [1024it] [181.51it/s]
[2026-03-29 09:27:28,786][onir_pt][DEBUG] [finished] training [5.65s]
[2026-03-29 09:27:28,787][onir_pt][INFO] training   it=11 loss=0.2267
[2026-03-29 09:27:28,787][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:27:28,787][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:27:28,787][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:27:42,731][onir_pt][DEBUG] [finished] batches: [13.94s] [6250it] [448.24it/s]
[2026-03-29 09:27:42,814][onir_pt][DEBUG] [finished] validation [14.03s]
[2026-03-29 09:27:42,816][onir_pt][INFO] validation it=11 map=0.0598 ndcg=0.1590 P_10=0.0262 <--
[2026-03-29 09:27:42,816][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:27:42,816][onir_pt][DEBUG] [starting] training
[2026-03-29 09:27:42,816][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:27:48,730][onir_pt][DEBUG] [finished] train pairs: [5.91s] [1024it] [173.17it/s]
[2026-03-29 09:27:48,732][onir_pt][DEBUG] [finished] training [5.92s]
[2026-03-29 09:27:48,732][onir_pt][INFO] training   it=12 loss=0.2192
[2026-03-29 09:27:48,732][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:27:48,732][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:27:48,733][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:28:03,000][onir_pt][DEBUG] [finished] batches: [14.27s] [6250it] [438.10it/s]
[2026-03-29 09:28:03,092][onir_pt][DEBUG] [finished] validation [14.36s]
[2026-03-29 09:28:03,093][onir_pt][INFO] validation it=12 map=0.0579 ndcg=0.1576 P_10=0.0258
[2026-03-29 09:28:03,093][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:28:03,094][onir_pt][DEBUG] [starting] training
[2026-03-29 09:28:03,094][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [11ms<?, ?it/s]

[2026-03-29 09:28:08,769][onir_pt][DEBUG] [finished] train pairs: [5.67s] [1024it] [180.46it/s]
[2026-03-29 09:28:08,771][onir_pt][DEBUG] [finished] training [5.68s]
[2026-03-29 09:28:08,772][onir_pt][INFO] training   it=13 loss=0.2407
[2026-03-29 09:28:08,772][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:28:08,773][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:28:08,773][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:28:22,812][onir_pt][DEBUG] [finished] batches: [14.04s] [6250it] [445.21it/s]
[2026-03-29 09:28:22,897][onir_pt][DEBUG] [finished] validation [14.12s]
[2026-03-29 09:28:22,899][onir_pt][INFO] validation it=13 map=0.0664 ndcg=0.1653 P_10=0.0276 <--
[2026-03-29 09:28:22,899][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:28:22,900][onir_pt][DEBUG] [starting] training
[2026-03-29 09:28:22,900][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [10ms<?, ?it/s]

[2026-03-29 09:28:29,966][onir_pt][DEBUG] [finished] train pairs: [7.07s] [1024it] [144.93it/s]
[2026-03-29 09:28:29,967][onir_pt][DEBUG] [finished] training [7.07s]
[2026-03-29 09:28:29,967][onir_pt][INFO] training   it=14 loss=0.2201
[2026-03-29 09:28:29,968][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:28:29,968][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:28:29,968][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:28:44,196][onir_pt][DEBUG] [finished] batches: [14.23s] [6250it] [439.30it/s]
[2026-03-29 09:28:44,278][onir_pt][DEBUG] [finished] validation [14.31s]
[2026-03-29 09:28:44,280][onir_pt][INFO] validation it=14 map=0.0670 ndcg=0.1661 P_10=0.0272 <--
[2026-03-29 09:28:44,280][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:28:44,280][onir_pt][DEBUG] [starting] training
[2026-03-29 09:28:44,280][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:28:49,832][onir_pt][DEBUG] [finished] train pairs: [5.55s] [1024it] [184.45it/s]
[2026-03-29 09:28:49,834][onir_pt][DEBUG] [finished] training [5.55s]
[2026-03-29 09:28:49,835][onir_pt][INFO] training   it=15 loss=0.2249
[2026-03-29 09:28:49,835][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:28:49,835][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:28:49,836][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:29:04,286][onir_pt][DEBUG] [finished] batches: [14.45s] [6250it] [432.52it/s]
[2026-03-29 09:29:04,385][onir_pt][DEBUG] [finished] validation [14.55s]
[2026-03-29 09:29:04,385][onir_pt][INFO] validation it=15 map=0.0633 ndcg=0.1626 P_10=0.0274
[2026-03-29 09:29:04,386][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:29:04,386][onir_pt][DEBUG] [starting] training
[2026-03-29 09:29:04,386][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:29:10,756][onir_pt][DEBUG] [finished] train pairs: [6.37s] [1024it] [160.77it/s]
[2026-03-29 09:29:10,761][onir_pt][DEBUG] [finished] training [6.38s]
[2026-03-29 09:29:10,762][onir_pt][INFO] training   it=16 loss=0.2160
[2026-03-29 09:29:10,762][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:29:10,762][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:29:10,763][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [16ms<?, ?it/s]

[2026-03-29 09:29:25,119][onir_pt][DEBUG] [finished] batches: [14.36s] [6250it] [435.34it/s]
[2026-03-29 09:29:25,206][onir_pt][DEBUG] [finished] validation [14.44s]
[2026-03-29 09:29:25,206][onir_pt][INFO] validation it=16 map=0.0650 ndcg=0.1637 P_10=0.0284
[2026-03-29 09:29:25,206][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:29:25,207][onir_pt][DEBUG] [starting] training
[2026-03-29 09:29:25,207][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [7ms<?, ?it/s]

[2026-03-29 09:29:31,331][onir_pt][DEBUG] [finished] train pairs: [6.12s] [1024it] [167.22it/s]
[2026-03-29 09:29:31,332][onir_pt][DEBUG] [finished] training [6.13s]
[2026-03-29 09:29:31,333][onir_pt][INFO] training   it=17 loss=0.2189
[2026-03-29 09:29:31,335][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:29:31,335][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:29:31,336][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:29:46,448][onir_pt][DEBUG] [finished] batches: [15.11s] [6250it] [413.60it/s]
[2026-03-29 09:29:46,604][onir_pt][DEBUG] [finished] validation [15.27s]
[2026-03-29 09:29:46,606][onir_pt][INFO] validation it=17 map=0.0750 ndcg=0.1730 P_10=0.0320 <--
[2026-03-29 09:29:46,606][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:29:46,606][onir_pt][DEBUG] [starting] training
[2026-03-29 09:29:46,607][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [10ms<?, ?it/s]

[2026-03-29 09:29:52,895][onir_pt][DEBUG] [finished] train pairs: [6.29s] [1024it] [162.83it/s]
[2026-03-29 09:29:52,897][onir_pt][DEBUG] [finished] training [6.29s]
[2026-03-29 09:29:52,898][onir_pt][INFO] training   it=18 loss=0.2112
[2026-03-29 09:29:52,898][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:29:52,898][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:29:52,899][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:30:07,187][onir_pt][DEBUG] [finished] batches: [14.29s] [6250it] [437.45it/s]
[2026-03-29 09:30:07,273][onir_pt][DEBUG] [finished] validation [14.38s]
[2026-03-29 09:30:07,274][onir_pt][INFO] validation it=18 map=0.0738 ndcg=0.1726 P_10=0.0340
[2026-03-29 09:30:07,274][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:30:07,274][onir_pt][DEBUG] [starting] training
[2026-03-29 09:30:07,274][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:30:14,079][onir_pt][DEBUG] [finished] train pairs: [6.80s] [1024it] [150.50it/s]
[2026-03-29 09:30:14,081][onir_pt][DEBUG] [finished] training [6.81s]
[2026-03-29 09:30:14,081][onir_pt][INFO] training   it=19 loss=0.2121
[2026-03-29 09:30:14,081][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:30:14,081][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:30:14,082][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:30:29,140][onir_pt][DEBUG] [finished] batches: [15.06s] [6250it] [415.06it/s]
[2026-03-29 09:30:29,228][onir_pt][DEBUG] [finished] validation [15.15s]
[2026-03-29 09:30:29,228][onir_pt][INFO] validation it=19 map=0.0740 ndcg=0.1726 P_10=0.0348
[2026-03-29 09:30:29,228][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:30:29,229][onir_pt][DEBUG] [starting] training
[2026-03-29 09:30:29,229][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:30:35,325][onir_pt][DEBUG] [finished] train pairs: [6.10s] [1024it] [167.99it/s]
[2026-03-29 09:30:35,328][onir_pt][DEBUG] [finished] training [6.10s]
[2026-03-29 09:30:35,328][onir_pt][INFO] training   it=20 loss=0.2146
[2026-03-29 09:30:35,329][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:30:35,329][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:30:35,330][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [16ms<?, ?it/s]

[2026-03-29 09:30:50,046][onir_pt][DEBUG] [finished] batches: [14.72s] [6250it] [424.72it/s]
[2026-03-29 09:30:50,138][onir_pt][DEBUG] [finished] validation [14.81s]
[2026-03-29 09:30:50,139][onir_pt][INFO] validation it=20 map=0.0702 ndcg=0.1691 P_10=0.0326
[2026-03-29 09:30:50,139][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:30:50,139][onir_pt][DEBUG] [starting] training
[2026-03-29 09:30:50,139][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:30:56,922][onir_pt][DEBUG] [finished] train pairs: [6.78s] [1024it] [150.98it/s]
[2026-03-29 09:30:56,924][onir_pt][DEBUG] [finished] training [6.78s]
[2026-03-29 09:30:56,925][onir_pt][INFO] training   it=21 loss=0.1975
[2026-03-29 09:30:56,925][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:30:56,925][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:30:56,926][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:31:11,721][onir_pt][DEBUG] [finished] batches: [14.79s] [6250it] [422.46it/s]
[2026-03-29 09:31:11,808][onir_pt][DEBUG] [finished] validation [14.88s]
[2026-03-29 09:31:11,808][onir_pt][INFO] validation it=21 map=0.0729 ndcg=0.1721 P_10=0.0336
[2026-03-29 09:31:11,808][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:31:11,809][onir_pt][DEBUG] [starting] training
[2026-03-29 09:31:11,809][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:31:17,951][onir_pt][DEBUG] [finished] train pairs: [6.14s] [1024it] [166.73it/s]
[2026-03-29 09:31:17,952][onir_pt][DEBUG] [finished] training [6.14s]
[2026-03-29 09:31:17,953][onir_pt][INFO] training   it=22 loss=0.2020
[2026-03-29 09:31:17,953][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:31:17,954][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:31:17,954][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [8ms<?, ?it/s]

[2026-03-29 09:31:33,130][onir_pt][DEBUG] [finished] batches: [15.18s] [6250it] [411.86it/s]
[2026-03-29 09:31:33,278][onir_pt][DEBUG] [finished] validation [15.33s]
[2026-03-29 09:31:33,279][onir_pt][INFO] validation it=22 map=0.0719 ndcg=0.1713 P_10=0.0302
[2026-03-29 09:31:33,279][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:31:33,280][onir_pt][DEBUG] [starting] training
[2026-03-29 09:31:33,280][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:31:39,666][onir_pt][DEBUG] [finished] train pairs: [6.39s] [1024it] [160.36it/s]
[2026-03-29 09:31:39,667][onir_pt][DEBUG] [finished] training [6.39s]
[2026-03-29 09:31:39,668][onir_pt][INFO] training   it=23 loss=0.2039
[2026-03-29 09:31:39,668][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:31:39,668][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:31:39,669][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:31:54,148][onir_pt][DEBUG] [finished] batches: [14.48s] [6250it] [431.66it/s]
[2026-03-29 09:31:54,241][onir_pt][DEBUG] [finished] validation [14.57s]
[2026-03-29 09:31:54,241][onir_pt][INFO] validation it=23 map=0.0739 ndcg=0.1730 P_10=0.0334
[2026-03-29 09:31:54,241][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:31:54,242][onir_pt][DEBUG] [starting] training
[2026-03-29 09:31:54,242][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:32:00,917][onir_pt][DEBUG] [finished] train pairs: [6.68s] [1024it] [153.40it/s]
[2026-03-29 09:32:00,920][onir_pt][DEBUG] [finished] training [6.68s]
[2026-03-29 09:32:00,921][onir_pt][INFO] training   it=24 loss=0.2091
[2026-03-29 09:32:00,921][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:32:00,921][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:32:00,921][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [15ms<?, ?it/s]

[2026-03-29 09:32:15,845][onir_pt][DEBUG] [finished] batches: [14.92s] [6250it] [418.82it/s]
[2026-03-29 09:32:15,930][onir_pt][DEBUG] [finished] validation [15.01s]
[2026-03-29 09:32:15,930][onir_pt][INFO] validation it=24 map=0.0645 ndcg=0.1632 P_10=0.0270
[2026-03-29 09:32:15,931][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:32:15,931][onir_pt][DEBUG] [starting] training
[2026-03-29 09:32:15,931][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:32:21,970][onir_pt][DEBUG] [finished] train pairs: [6.04s] [1024it] [169.56it/s]
[2026-03-29 09:32:21,972][onir_pt][DEBUG] [finished] training [6.04s]
[2026-03-29 09:32:21,973][onir_pt][INFO] training   it=25 loss=0.2126
[2026-03-29 09:32:21,973][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:32:21,974][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:32:21,974][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:32:36,492][onir_pt][DEBUG] [finished] batches: [14.52s] [6250it] [430.52it/s]
[2026-03-29 09:32:36,577][onir_pt][DEBUG] [finished] validation [14.60s]
[2026-03-29 09:32:36,578][onir_pt][INFO] validation it=25 map=0.0748 ndcg=0.1729 P_10=0.0306
[2026-03-29 09:32:36,578][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:32:36,579][onir_pt][DEBUG] [starting] training
[2026-03-29 09:32:36,579][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:32:43,452][onir_pt][DEBUG] [finished] train pairs: [6.87s] [1024it] [149.00it/s]
[2026-03-29 09:32:43,454][onir_pt][DEBUG] [finished] training [6.88s]
[2026-03-29 09:32:43,457][onir_pt][INFO] training   it=26 loss=0.2005
[2026-03-29 09:32:43,457][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:32:43,457][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:32:43,458][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:32:58,017][onir_pt][DEBUG] [finished] batches: [14.56s] [6250it] [429.30it/s]
[2026-03-29 09:32:58,183][onir_pt][DEBUG] [finished] validation [14.73s]
[2026-03-29 09:32:58,187][onir_pt][INFO] validation it=26 map=0.0903 ndcg=0.1880 P_10=0.0372 <--
[2026-03-29 09:32:58,187][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:32:58,188][onir_pt][DEBUG] [starting] training
[2026-03-29 09:32:58,188][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [9ms<?, ?it/s]

[2026-03-29 09:33:04,485][onir_pt][DEBUG] [finished] train pairs: [6.30s] [1024it] [162.62it/s]
[2026-03-29 09:33:04,487][onir_pt][DEBUG] [finished] training [6.30s]
[2026-03-29 09:33:04,487][onir_pt][INFO] training   it=27 loss=0.1393
[2026-03-29 09:33:04,488][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:33:04,488][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:33:04,489][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:33:19,514][onir_pt][DEBUG] [finished] batches: [15.02s] [6250it] [415.98it/s]
[2026-03-29 09:33:19,668][onir_pt][DEBUG] [finished] validation [15.18s]
[2026-03-29 09:33:19,670][onir_pt][INFO] validation it=27 map=0.1730 ndcg=0.2637 P_10=0.0588 <--
[2026-03-29 09:33:19,670][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:33:19,671][onir_pt][DEBUG] [starting] training
[2026-03-29 09:33:19,671][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:33:26,254][onir_pt][DEBUG] [finished] train pairs: [6.58s] [1024it] [155.54it/s]
[2026-03-29 09:33:26,257][onir_pt][DEBUG] [finished] training [6.59s]
[2026-03-29 09:33:26,258][onir_pt][INFO] training   it=28 loss=0.1252
[2026-03-29 09:33:26,258][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:33:26,258][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:33:26,259][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:33:40,600][onir_pt][DEBUG] [finished] batches: [14.34s] [6250it] [435.82it/s]
[2026-03-29 09:33:40,685][onir_pt][DEBUG] [finished] validation [14.43s]
[2026-03-29 09:33:40,685][onir_pt][INFO] validation it=28 map=0.1608 ndcg=0.2529 P_10=0.0546
[2026-03-29 09:33:40,685][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:33:40,686][onir_pt][DEBUG] [starting] training
[2026-03-29 09:33:40,686][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:33:47,026][onir_pt][DEBUG] [finished] train pairs: [6.34s] [1024it] [161.52it/s]
[2026-03-29 09:33:47,028][onir_pt][DEBUG] [finished] training [6.34s]
[2026-03-29 09:33:47,028][onir_pt][INFO] training   it=29 loss=0.1298
[2026-03-29 09:33:47,028][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:33:47,028][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:33:47,029][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:34:01,964][onir_pt][DEBUG] [finished] batches: [14.93s] [6250it] [418.51it/s]
[2026-03-29 09:34:02,050][onir_pt][DEBUG] [finished] validation [15.02s]
[2026-03-29 09:34:02,051][onir_pt][INFO] validation it=29 map=0.1789 ndcg=0.2680 P_10=0.0590 <--
[2026-03-29 09:34:02,052][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:34:02,052][onir_pt][DEBUG] [starting] training
[2026-03-29 09:34:02,052][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:34:08,258][onir_pt][DEBUG] [finished] train pairs: [6.21s] [1024it] [165.01it/s]
[2026-03-29 09:34:08,262][onir_pt][DEBUG] [finished] training [6.21s]
[2026-03-29 09:34:08,263][onir_pt][INFO] training   it=30 loss=0.1170
[2026-03-29 09:34:08,264][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:34:08,264][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:34:08,264][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [15ms<?, ?it/s]

[2026-03-29 09:34:22,670][onir_pt][DEBUG] [finished] batches: [14.40s] [6250it] [433.88it/s]
[2026-03-29 09:34:22,756][onir_pt][DEBUG] [finished] validation [14.49s]
[2026-03-29 09:34:22,758][onir_pt][INFO] validation it=30 map=0.1844 ndcg=0.2731 P_10=0.0602 <--
[2026-03-29 09:34:22,758][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:34:22,759][onir_pt][DEBUG] [starting] training
[2026-03-29 09:34:22,759][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:34:29,942][onir_pt][DEBUG] [finished] train pairs: [7.18s] [1024it] [142.56it/s]
[2026-03-29 09:34:29,943][onir_pt][DEBUG] [finished] training [7.18s]
[2026-03-29 09:34:29,944][onir_pt][INFO] training   it=31 loss=0.1250
[2026-03-29 09:34:29,944][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:34:29,945][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:34:29,945][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:34:44,435][onir_pt][DEBUG] [finished] batches: [14.49s] [6250it] [431.37it/s]
[2026-03-29 09:34:44,523][onir_pt][DEBUG] [finished] validation [14.58s]
[2026-03-29 09:34:44,525][onir_pt][INFO] validation it=31 map=0.1853 ndcg=0.2739 P_10=0.0604 <--
[2026-03-29 09:34:44,525][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:34:44,525][onir_pt][DEBUG] [starting] training
[2026-03-29 09:34:44,525][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:34:50,749][onir_pt][DEBUG] [finished] train pairs: [6.22s] [1024it] [164.53it/s]
[2026-03-29 09:34:50,753][onir_pt][DEBUG] [finished] training [6.23s]
[2026-03-29 09:34:50,754][onir_pt][INFO] training   it=32 loss=0.1104
[2026-03-29 09:34:50,755][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:34:50,755][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:34:50,756][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:35:05,741][onir_pt][DEBUG] [finished] batches: [14.99s] [6250it] [417.08it/s]
[2026-03-29 09:35:05,903][onir_pt][DEBUG] [finished] validation [15.15s]
[2026-03-29 09:35:05,904][onir_pt][INFO] validation it=32 map=0.1848 ndcg=0.2734 P_10=0.0596
[2026-03-29 09:35:05,904][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:35:05,904][onir_pt][DEBUG] [starting] training
[2026-03-29 09:35:05,905][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:35:12,000][onir_pt][DEBUG] [finished] train pairs: [6.10s] [1024it] [168.00it/s]
[2026-03-29 09:35:12,002][onir_pt][DEBUG] [finished] training [6.10s]
[2026-03-29 09:35:12,003][onir_pt][INFO] training   it=33 loss=0.1192
[2026-03-29 09:35:12,003][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:35:12,003][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:35:12,004][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:35:26,289][onir_pt][DEBUG] [finished] batches: [14.29s] [6250it] [437.52it/s]
[2026-03-29 09:35:26,376][onir_pt][DEBUG] [finished] validation [14.37s]
[2026-03-29 09:35:26,377][onir_pt][INFO] validation it=33 map=0.1822 ndcg=0.2720 P_10=0.0600
[2026-03-29 09:35:26,377][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:35:26,377][onir_pt][DEBUG] [starting] training
[2026-03-29 09:35:26,377][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:35:32,391][onir_pt][DEBUG] [finished] train pairs: [6.01s] [1024it] [170.30it/s]
[2026-03-29 09:35:32,392][onir_pt][DEBUG] [finished] training [6.01s]
[2026-03-29 09:35:32,393][onir_pt][INFO] training   it=34 loss=0.1138
[2026-03-29 09:35:32,393][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:35:32,393][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:35:32,394][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:35:47,319][onir_pt][DEBUG] [finished] batches: [14.93s] [6250it] [418.75it/s]
[2026-03-29 09:35:47,406][onir_pt][DEBUG] [finished] validation [15.01s]
[2026-03-29 09:35:47,408][onir_pt][INFO] validation it=34 map=0.1880 ndcg=0.2773 P_10=0.0618 <--
[2026-03-29 09:35:47,408][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:35:47,408][onir_pt][DEBUG] [starting] training
[2026-03-29 09:35:47,408][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:35:53,335][onir_pt][DEBUG] [finished] train pairs: [5.93s] [1024it] [172.78it/s]
[2026-03-29 09:35:53,336][onir_pt][DEBUG] [finished] training [5.93s]
[2026-03-29 09:35:53,337][onir_pt][INFO] training   it=35 loss=0.1161
[2026-03-29 09:35:53,338][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:35:53,338][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:35:53,338][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:36:07,746][onir_pt][DEBUG] [finished] batches: [14.41s] [6250it] [433.80it/s]
[2026-03-29 09:36:07,851][onir_pt][DEBUG] [finished] validation [14.51s]
[2026-03-29 09:36:07,853][onir_pt][INFO] validation it=35 map=0.1884 ndcg=0.2771 P_10=0.0622 <--
[2026-03-29 09:36:07,853][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:36:07,853][onir_pt][DEBUG] [starting] training
[2026-03-29 09:36:07,853][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:36:14,399][onir_pt][DEBUG] [finished] train pairs: [6.55s] [1024it] [156.44it/s]
[2026-03-29 09:36:14,402][onir_pt][DEBUG] [finished] training [6.55s]
[2026-03-29 09:36:14,403][onir_pt][INFO] training   it=36 loss=0.1170
[2026-03-29 09:36:14,403][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:36:14,404][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:36:14,405][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:36:29,095][onir_pt][DEBUG] [finished] batches: [14.69s] [6250it] [425.47it/s]
[2026-03-29 09:36:29,181][onir_pt][DEBUG] [finished] validation [14.78s]
[2026-03-29 09:36:29,181][onir_pt][INFO] validation it=36 map=0.1777 ndcg=0.2675 P_10=0.0580
[2026-03-29 09:36:29,181][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:36:29,182][onir_pt][DEBUG] [starting] training
[2026-03-29 09:36:29,182][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:36:35,143][onir_pt][DEBUG] [finished] train pairs: [5.96s] [1024it] [171.80it/s]
[2026-03-29 09:36:35,146][onir_pt][DEBUG] [finished] training [5.96s]
[2026-03-29 09:36:35,146][onir_pt][INFO] training   it=37 loss=0.1117
[2026-03-29 09:36:35,146][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:36:35,146][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:36:35,147][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [17ms<?, ?it/s]

[2026-03-29 09:36:49,594][onir_pt][DEBUG] [finished] batches: [14.45s] [6250it] [432.64it/s]
[2026-03-29 09:36:49,681][onir_pt][DEBUG] [finished] validation [14.53s]
[2026-03-29 09:36:49,683][onir_pt][INFO] validation it=37 map=0.1927 ndcg=0.2809 P_10=0.0626 <--
[2026-03-29 09:36:49,683][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:36:49,683][onir_pt][DEBUG] [starting] training
[2026-03-29 09:36:49,683][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:36:56,060][onir_pt][DEBUG] [finished] train pairs: [6.38s] [1024it] [160.60it/s]
[2026-03-29 09:36:56,062][onir_pt][DEBUG] [finished] training [6.38s]
[2026-03-29 09:36:56,062][onir_pt][INFO] training   it=38 loss=0.1125
[2026-03-29 09:36:56,063][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:36:56,063][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:36:56,063][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:37:10,738][onir_pt][DEBUG] [finished] batches: [14.67s] [6250it] [425.90it/s]
[2026-03-29 09:37:10,826][onir_pt][DEBUG] [finished] validation [14.76s]
[2026-03-29 09:37:10,826][onir_pt][INFO] validation it=38 map=0.1916 ndcg=0.2790 P_10=0.0606
[2026-03-29 09:37:10,826][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:37:10,827][onir_pt][DEBUG] [starting] training
[2026-03-29 09:37:10,827][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:37:16,730][onir_pt][DEBUG] [finished] train pairs: [5.90s] [1024it] [173.49it/s]
[2026-03-29 09:37:16,733][onir_pt][DEBUG] [finished] training [5.91s]
[2026-03-29 09:37:16,733][onir_pt][INFO] training   it=39 loss=0.1131
[2026-03-29 09:37:16,734][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:37:16,734][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:37:16,734][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [14ms<?, ?it/s]

[2026-03-29 09:37:31,171][onir_pt][DEBUG] [finished] batches: [14.44s] [6250it] [432.93it/s]
[2026-03-29 09:37:31,315][onir_pt][DEBUG] [finished] validation [14.58s]
[2026-03-29 09:37:31,317][onir_pt][INFO] validation it=39 map=0.1947 ndcg=0.2827 P_10=0.0626 <--
[2026-03-29 09:37:31,317][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:37:31,318][onir_pt][DEBUG] [starting] training
[2026-03-29 09:37:31,318][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [17ms<?, ?it/s]

[2026-03-29 09:37:37,614][onir_pt][DEBUG] [finished] train pairs: [6.30s] [1024it] [162.64it/s]
[2026-03-29 09:37:37,616][onir_pt][DEBUG] [finished] training [6.30s]
[2026-03-29 09:37:37,617][onir_pt][INFO] training   it=40 loss=0.1215
[2026-03-29 09:37:37,617][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:37:37,617][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:37:37,618][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:37:52,131][onir_pt][DEBUG] [finished] batches: [14.51s] [6250it] [430.66it/s]
[2026-03-29 09:37:52,220][onir_pt][DEBUG] [finished] validation [14.60s]
[2026-03-29 09:37:52,220][onir_pt][INFO] validation it=40 map=0.1897 ndcg=0.2781 P_10=0.0596
[2026-03-29 09:37:52,220][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:37:52,221][onir_pt][DEBUG] [starting] training
[2026-03-29 09:37:52,221][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:37:58,406][onir_pt][DEBUG] [finished] train pairs: [6.18s] [1024it] [165.57it/s]
[2026-03-29 09:37:58,408][onir_pt][DEBUG] [finished] training [6.19s]
[2026-03-29 09:37:58,410][onir_pt][INFO] training   it=41 loss=0.1153
[2026-03-29 09:37:58,410][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:37:58,410][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:37:58,411][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:38:13,736][onir_pt][DEBUG] [finished] batches: [15.33s] [6250it] [407.82it/s]
[2026-03-29 09:38:13,822][onir_pt][DEBUG] [finished] validation [15.41s]
[2026-03-29 09:38:13,823][onir_pt][INFO] validation it=41 map=0.1931 ndcg=0.2811 P_10=0.0612
[2026-03-29 09:38:13,823][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:38:13,823][onir_pt][DEBUG] [starting] training
[2026-03-29 09:38:13,823][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:38:19,913][onir_pt][DEBUG] [finished] train pairs: [6.09s] [1024it] [168.14it/s]
[2026-03-29 09:38:19,915][onir_pt][DEBUG] [finished] training [6.09s]
[2026-03-29 09:38:19,915][onir_pt][INFO] training   it=42 loss=0.1001
[2026-03-29 09:38:19,915][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:38:19,915][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:38:19,916][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:38:34,258][onir_pt][DEBUG] [finished] batches: [14.34s] [6250it] [435.79it/s]
[2026-03-29 09:38:34,345][onir_pt][DEBUG] [finished] validation [14.43s]
[2026-03-29 09:38:34,347][onir_pt][INFO] validation it=42 map=0.1994 ndcg=0.2863 P_10=0.0620 <--
[2026-03-29 09:38:34,347][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:38:34,348][onir_pt][DEBUG] [starting] training
[2026-03-29 09:38:34,348][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:38:40,663][onir_pt][DEBUG] [finished] train pairs: [6.31s] [1024it] [162.17it/s]
[2026-03-29 09:38:40,664][onir_pt][DEBUG] [finished] training [6.32s]
[2026-03-29 09:38:40,665][onir_pt][INFO] training   it=43 loss=0.1127
[2026-03-29 09:38:40,665][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:38:40,666][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:38:40,666][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [15ms<?, ?it/s]

[2026-03-29 09:38:55,828][onir_pt][DEBUG] [finished] batches: [15.16s] [6250it] [412.24it/s]
[2026-03-29 09:38:55,912][onir_pt][DEBUG] [finished] validation [15.25s]
[2026-03-29 09:38:55,913][onir_pt][INFO] validation it=43 map=0.1781 ndcg=0.2684 P_10=0.0594
[2026-03-29 09:38:55,913][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:38:55,913][onir_pt][DEBUG] [starting] training
[2026-03-29 09:38:55,914][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:39:01,867][onir_pt][DEBUG] [finished] train pairs: [5.95s] [1024it] [172.02it/s]
[2026-03-29 09:39:01,869][onir_pt][DEBUG] [finished] training [5.96s]
[2026-03-29 09:39:01,869][onir_pt][INFO] training   it=44 loss=0.1093
[2026-03-29 09:39:01,869][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:39:01,869][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:39:01,870][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:39:16,454][onir_pt][DEBUG] [finished] batches: [14.58s] [6250it] [428.57it/s]
[2026-03-29 09:39:16,536][onir_pt][DEBUG] [finished] validation [14.67s]
[2026-03-29 09:39:16,537][onir_pt][INFO] validation it=44 map=0.1953 ndcg=0.2830 P_10=0.0618
[2026-03-29 09:39:16,537][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:39:16,537][onir_pt][DEBUG] [starting] training
[2026-03-29 09:39:16,537][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:39:23,133][onir_pt][DEBUG] [finished] train pairs: [6.60s] [1024it] [155.25it/s]
[2026-03-29 09:39:23,136][onir_pt][DEBUG] [finished] training [6.60s]
[2026-03-29 09:39:23,136][onir_pt][INFO] training   it=45 loss=0.1154
[2026-03-29 09:39:23,136][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:39:23,137][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:39:23,137][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:39:39,296][onir_pt][DEBUG] [finished] batches: [16.16s] [6250it] [386.79it/s]
[2026-03-29 09:39:39,381][onir_pt][DEBUG] [finished] validation [16.24s]
[2026-03-29 09:39:39,382][onir_pt][INFO] validation it=45 map=0.1817 ndcg=0.2713 P_10=0.0606
[2026-03-29 09:39:39,382][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:39:39,383][onir_pt][DEBUG] [starting] training
[2026-03-29 09:39:39,383][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:39:45,462][onir_pt][DEBUG] [finished] train pairs: [6.08s] [1024it] [168.45it/s]
[2026-03-29 09:39:45,464][onir_pt][DEBUG] [finished] training [6.08s]
[2026-03-29 09:39:45,464][onir_pt][INFO] training   it=46 loss=0.1133
[2026-03-29 09:39:45,464][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:39:45,464][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:39:45,465][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:40:01,293][onir_pt][DEBUG] [finished] batches: [15.83s] [6250it] [394.86it/s]
[2026-03-29 09:40:01,476][onir_pt][DEBUG] [finished] validation [16.01s]
[2026-03-29 09:40:01,478][onir_pt][INFO] validation it=46 map=0.1879 ndcg=0.2765 P_10=0.0610
[2026-03-29 09:40:01,478][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:40:01,479][onir_pt][DEBUG] [starting] training
[2026-03-29 09:40:01,479][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [27ms<?, ?it/s]

[2026-03-29 09:40:09,446][onir_pt][DEBUG] [finished] train pairs: [7.97s] [1024it] [128.54it/s]
[2026-03-29 09:40:09,448][onir_pt][DEBUG] [finished] training [7.97s]
[2026-03-29 09:40:09,449][onir_pt][INFO] training   it=47 loss=0.1047
[2026-03-29 09:40:09,449][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:40:09,449][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:40:09,450][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:40:26,451][onir_pt][DEBUG] [finished] batches: [17.00s] [6250it] [367.63it/s]
[2026-03-29 09:40:26,553][onir_pt][DEBUG] [finished] validation [17.10s]
[2026-03-29 09:40:26,553][onir_pt][INFO] validation it=47 map=0.1940 ndcg=0.2819 P_10=0.0630
[2026-03-29 09:40:26,554][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:40:26,554][onir_pt][DEBUG] [starting] training
[2026-03-29 09:40:26,554][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:40:32,710][onir_pt][DEBUG] [finished] train pairs: [6.16s] [1024it] [166.36it/s]
[2026-03-29 09:40:32,711][onir_pt][DEBUG] [finished] training [6.16s]
[2026-03-29 09:40:32,712][onir_pt][INFO] training   it=48 loss=0.1132
[2026-03-29 09:40:32,712][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:40:32,712][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:40:32,713][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:40:47,777][onir_pt][DEBUG] [finished] batches: [15.06s] [6250it] [414.90it/s]
[2026-03-29 09:40:47,862][onir_pt][DEBUG] [finished] validation [15.15s]
[2026-03-29 09:40:47,862][onir_pt][INFO] validation it=48 map=0.1971 ndcg=0.2847 P_10=0.0640
[2026-03-29 09:40:47,862][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:40:47,863][onir_pt][DEBUG] [starting] training
[2026-03-29 09:40:47,863][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:40:53,693][onir_pt][DEBUG] [finished] train pairs: [5.83s] [1024it] [175.65it/s]
[2026-03-29 09:40:53,696][onir_pt][DEBUG] [finished] training [5.83s]
[2026-03-29 09:40:53,697][onir_pt][INFO] training   it=49 loss=0.1069
[2026-03-29 09:40:53,697][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:40:53,697][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:40:53,697][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:41:09,253][onir_pt][DEBUG] [finished] batches: [15.55s] [6250it] [401.80it/s]
[2026-03-29 09:41:09,341][onir_pt][DEBUG] [finished] validation [15.64s]
[2026-03-29 09:41:09,341][onir_pt][INFO] validation it=49 map=0.1915 ndcg=0.2794 P_10=0.0622
[2026-03-29 09:41:09,342][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:41:09,342][onir_pt][DEBUG] [starting] training
[2026-03-29 09:41:09,342][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:41:16,200][onir_pt][DEBUG] [finished] train pairs: [6.86s] [1024it] [149.31it/s]
[2026-03-29 09:41:16,203][onir_pt][DEBUG] [finished] training [6.86s]
[2026-03-29 09:41:16,203][onir_pt][INFO] training   it=50 loss=0.1084
[2026-03-29 09:41:16,203][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:41:16,203][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:41:16,204][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:41:33,735][onir_pt][DEBUG] [finished] batches: [17.53s] [6250it] [356.53it/s]
[2026-03-29 09:41:33,825][onir_pt][DEBUG] [finished] validation [17.62s]
[2026-03-29 09:41:33,826][onir_pt][INFO] validation it=50 map=0.1918 ndcg=0.2797 P_10=0.0612
[2026-03-29 09:41:33,826][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:41:33,826][onir_pt][DEBUG] [starting] training
[2026-03-29 09:41:33,826][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:41:39,768][onir_pt][DEBUG] [finished] train pairs: [5.94s] [1024it] [172.33it/s]
[2026-03-29 09:41:39,771][onir_pt][DEBUG] [finished] training [5.95s]
[2026-03-29 09:41:39,771][onir_pt][INFO] training   it=51 loss=0.1101
[2026-03-29 09:41:39,772][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:41:39,772][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:41:39,772][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:41:54,922][onir_pt][DEBUG] [finished] batches: [15.15s] [6250it] [412.57it/s]
[2026-03-29 09:41:55,010][onir_pt][DEBUG] [finished] validation [15.24s]
[2026-03-29 09:41:55,011][onir_pt][INFO] validation it=51 map=0.1848 ndcg=0.2739 P_10=0.0610
[2026-03-29 09:41:55,011][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:41:55,011][onir_pt][DEBUG] [starting] training
[2026-03-29 09:41:55,011][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:42:01,342][onir_pt][DEBUG] [finished] train pairs: [6.33s] [1024it] [161.75it/s]
[2026-03-29 09:42:01,345][onir_pt][DEBUG] [finished] training [6.33s]
[2026-03-29 09:42:01,345][onir_pt][INFO] training   it=52 loss=0.1202
[2026-03-29 09:42:01,345][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:42:01,345][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:42:01,346][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:42:19,462][onir_pt][DEBUG] [finished] batches: [18.12s] [6250it] [345.01it/s]
[2026-03-29 09:42:19,547][onir_pt][DEBUG] [finished] validation [18.20s]
[2026-03-29 09:42:19,549][onir_pt][INFO] validation it=52 map=0.1994 ndcg=0.2861 P_10=0.0634 <--
[2026-03-29 09:42:19,550][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:42:19,550][onir_pt][DEBUG] [starting] training
[2026-03-29 09:42:19,550][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:42:29,992][onir_pt][DEBUG] [finished] train pairs: [10.44s] [1024it] [98.07it/s]
[2026-03-29 09:42:29,994][onir_pt][DEBUG] [finished] training [10.44s]
[2026-03-29 09:42:29,994][onir_pt][INFO] training   it=53 loss=0.1119
[2026-03-29 09:42:29,994][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:42:29,994][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:42:29,995][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:42:45,534][onir_pt][DEBUG] [finished] batches: [15.54s] [6250it] [402.22it/s]
[2026-03-29 09:42:45,659][onir_pt][DEBUG] [finished] validation [15.67s]
[2026-03-29 09:42:45,660][onir_pt][INFO] validation it=53 map=0.1968 ndcg=0.2841 P_10=0.0626
[2026-03-29 09:42:45,660][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:42:45,660][onir_pt][DEBUG] [starting] training
[2026-03-29 09:42:45,660][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:42:52,237][onir_pt][DEBUG] [finished] train pairs: [6.58s] [1024it] [155.70it/s]
[2026-03-29 09:42:52,238][onir_pt][DEBUG] [finished] training [6.58s]
[2026-03-29 09:42:52,239][onir_pt][INFO] training   it=54 loss=0.1167
[2026-03-29 09:42:52,240][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:42:52,240][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:42:52,240][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [14ms<?, ?it/s]

[2026-03-29 09:43:08,331][onir_pt][DEBUG] [finished] batches: [16.09s] [6250it] [388.42it/s]
[2026-03-29 09:43:08,418][onir_pt][DEBUG] [finished] validation [16.18s]
[2026-03-29 09:43:08,420][onir_pt][INFO] validation it=54 map=0.2026 ndcg=0.2892 P_10=0.0646 <--
[2026-03-29 09:43:08,420][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:43:08,420][onir_pt][DEBUG] [starting] training
[2026-03-29 09:43:08,421][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:43:15,601][onir_pt][DEBUG] [finished] train pairs: [7.18s] [1024it] [142.61it/s]
[2026-03-29 09:43:15,609][onir_pt][DEBUG] [finished] training [7.19s]
[2026-03-29 09:43:15,609][onir_pt][INFO] training   it=55 loss=0.1201
[2026-03-29 09:43:15,610][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:43:15,610][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:43:15,611][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [22ms<?, ?it/s]

[2026-03-29 09:43:31,366][onir_pt][DEBUG] [finished] batches: [15.75s] [6250it] [396.70it/s]
[2026-03-29 09:43:31,518][onir_pt][DEBUG] [finished] validation [15.91s]
[2026-03-29 09:43:31,520][onir_pt][INFO] validation it=55 map=0.2063 ndcg=0.2924 P_10=0.0654 <--
[2026-03-29 09:43:31,520][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:43:31,521][onir_pt][DEBUG] [starting] training
[2026-03-29 09:43:31,521][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [13ms<?, ?it/s]

[2026-03-29 09:43:38,140][onir_pt][DEBUG] [finished] train pairs: [6.62s] [1024it] [154.73it/s]
[2026-03-29 09:43:38,142][onir_pt][DEBUG] [finished] training [6.62s]
[2026-03-29 09:43:38,142][onir_pt][INFO] training   it=56 loss=0.1136
[2026-03-29 09:43:38,142][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:43:38,142][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:43:38,143][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:43:53,901][onir_pt][DEBUG] [finished] batches: [15.76s] [6250it] [396.64it/s]
[2026-03-29 09:43:53,989][onir_pt][DEBUG] [finished] validation [15.85s]
[2026-03-29 09:43:53,990][onir_pt][INFO] validation it=56 map=0.2093 ndcg=0.2944 P_10=0.0654 <--
[2026-03-29 09:43:53,991][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:43:53,991][onir_pt][DEBUG] [starting] training
[2026-03-29 09:43:53,991][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:44:00,670][onir_pt][DEBUG] [finished] train pairs: [6.68s] [1024it] [153.34it/s]
[2026-03-29 09:44:00,672][onir_pt][DEBUG] [finished] training [6.68s]
[2026-03-29 09:44:00,672][onir_pt][INFO] training   it=57 loss=0.1199
[2026-03-29 09:44:00,672][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:44:00,673][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:44:00,673][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:44:16,490][onir_pt][DEBUG] [finished] batches: [15.82s] [6250it] [395.14it/s]
[2026-03-29 09:44:16,574][onir_pt][DEBUG] [finished] validation [15.90s]
[2026-03-29 09:44:16,575][onir_pt][INFO] validation it=57 map=0.2012 ndcg=0.2881 P_10=0.0624
[2026-03-29 09:44:16,575][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:44:16,575][onir_pt][DEBUG] [starting] training
[2026-03-29 09:44:16,575][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:44:22,368][onir_pt][DEBUG] [finished] train pairs: [5.79s] [1024it] [176.79it/s]
[2026-03-29 09:44:22,372][onir_pt][DEBUG] [finished] training [5.80s]
[2026-03-29 09:44:22,372][onir_pt][INFO] training   it=58 loss=0.1112
[2026-03-29 09:44:22,372][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:44:22,372][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:44:22,373][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [17ms<?, ?it/s]

[2026-03-29 09:44:37,444][onir_pt][DEBUG] [finished] batches: [15.07s] [6250it] [414.69it/s]
[2026-03-29 09:44:37,537][onir_pt][DEBUG] [finished] validation [15.16s]
[2026-03-29 09:44:37,538][onir_pt][INFO] validation it=58 map=0.2047 ndcg=0.2909 P_10=0.0642
[2026-03-29 09:44:37,538][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:44:37,538][onir_pt][DEBUG] [starting] training
[2026-03-29 09:44:37,539][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:44:44,373][onir_pt][DEBUG] [finished] train pairs: [6.83s] [1024it] [149.84it/s]
[2026-03-29 09:44:44,375][onir_pt][DEBUG] [finished] training [6.84s]
[2026-03-29 09:44:44,375][onir_pt][INFO] training   it=59 loss=0.1099
[2026-03-29 09:44:44,375][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:44:44,376][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:44:44,376][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:44:59,669][onir_pt][DEBUG] [finished] batches: [15.29s] [6250it] [408.71it/s]
[2026-03-29 09:44:59,758][onir_pt][DEBUG] [finished] validation [15.38s]
[2026-03-29 09:44:59,759][onir_pt][INFO] validation it=59 map=0.2085 ndcg=0.2941 P_10=0.0638
[2026-03-29 09:44:59,759][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:44:59,759][onir_pt][DEBUG] [starting] training
[2026-03-29 09:44:59,759][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:45:05,405][onir_pt][DEBUG] [finished] train pairs: [5.65s] [1024it] [181.39it/s]
[2026-03-29 09:45:05,407][onir_pt][DEBUG] [finished] training [5.65s]
[2026-03-29 09:45:05,407][onir_pt][INFO] training   it=60 loss=0.1088
[2026-03-29 09:45:05,407][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:45:05,407][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:45:05,408][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:45:20,838][onir_pt][DEBUG] [finished] batches: [15.43s] [6250it] [405.08it/s]
[2026-03-29 09:45:20,980][onir_pt][DEBUG] [finished] validation [15.57s]
[2026-03-29 09:45:20,980][onir_pt][INFO] validation it=60 map=0.2018 ndcg=0.2886 P_10=0.0624
[2026-03-29 09:45:20,980][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:45:20,981][onir_pt][DEBUG] [starting] training
[2026-03-29 09:45:20,981][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [7ms<?, ?it/s]

[2026-03-29 09:45:28,475][onir_pt][DEBUG] [finished] train pairs: [7.49s] [1024it] [136.66it/s]
[2026-03-29 09:45:28,478][onir_pt][DEBUG] [finished] training [7.50s]
[2026-03-29 09:45:28,478][onir_pt][INFO] training   it=61 loss=0.1201
[2026-03-29 09:45:28,478][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:45:28,478][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:45:28,479][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:45:43,305][onir_pt][DEBUG] [finished] batches: [14.83s] [6250it] [421.55it/s]
[2026-03-29 09:45:43,394][onir_pt][DEBUG] [finished] validation [14.92s]
[2026-03-29 09:45:43,395][onir_pt][INFO] validation it=61 map=0.2065 ndcg=0.2929 P_10=0.0634
[2026-03-29 09:45:43,395][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:45:43,395][onir_pt][DEBUG] [starting] training
[2026-03-29 09:45:43,395][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:45:49,692][onir_pt][DEBUG] [finished] train pairs: [6.30s] [1024it] [162.64it/s]
[2026-03-29 09:45:49,693][onir_pt][DEBUG] [finished] training [6.30s]
[2026-03-29 09:45:49,694][onir_pt][INFO] training   it=62 loss=0.1047
[2026-03-29 09:45:49,694][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:45:49,695][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:45:49,696][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:46:05,437][onir_pt][DEBUG] [finished] batches: [15.74s] [6250it] [397.05it/s]
[2026-03-29 09:46:05,526][onir_pt][DEBUG] [finished] validation [15.83s]
[2026-03-29 09:46:05,527][onir_pt][INFO] validation it=62 map=0.2045 ndcg=0.2908 P_10=0.0624
[2026-03-29 09:46:05,527][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:46:05,527][onir_pt][DEBUG] [starting] training
[2026-03-29 09:46:05,527][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:46:11,211][onir_pt][DEBUG] [finished] train pairs: [5.68s] [1024it] [180.17it/s]
[2026-03-29 09:46:11,213][onir_pt][DEBUG] [finished] training [5.69s]
[2026-03-29 09:46:11,213][onir_pt][INFO] training   it=63 loss=0.1184
[2026-03-29 09:46:11,213][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:46:11,214][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:46:11,215][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:46:29,265][onir_pt][DEBUG] [finished] batches: [18.05s] [6250it] [346.26it/s]
[2026-03-29 09:46:29,403][onir_pt][DEBUG] [finished] validation [18.19s]
[2026-03-29 09:46:29,404][onir_pt][INFO] validation it=63 map=0.2082 ndcg=0.2941 P_10=0.0658
[2026-03-29 09:46:29,404][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:46:29,404][onir_pt][DEBUG] [starting] training
[2026-03-29 09:46:29,405][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [10ms<?, ?it/s]

[2026-03-29 09:46:35,515][onir_pt][DEBUG] [finished] train pairs: [6.11s] [1024it] [167.58it/s]
[2026-03-29 09:46:35,517][onir_pt][DEBUG] [finished] training [6.11s]
[2026-03-29 09:46:35,518][onir_pt][INFO] training   it=64 loss=0.1104
[2026-03-29 09:46:35,518][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:46:35,518][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:46:35,519][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:46:50,885][onir_pt][DEBUG] [finished] batches: [15.37s] [6250it] [406.76it/s]
[2026-03-29 09:46:50,977][onir_pt][DEBUG] [finished] validation [15.46s]
[2026-03-29 09:46:50,978][onir_pt][INFO] validation it=64 map=0.2121 ndcg=0.2969 P_10=0.0648 <--
[2026-03-29 09:46:50,979][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:46:50,979][onir_pt][DEBUG] [starting] training
[2026-03-29 09:46:50,979][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:46:57,199][onir_pt][DEBUG] [finished] train pairs: [6.22s] [1024it] [164.63it/s]
[2026-03-29 09:46:57,201][onir_pt][DEBUG] [finished] training [6.22s]
[2026-03-29 09:46:57,201][onir_pt][INFO] training   it=65 loss=0.1185
[2026-03-29 09:46:57,202][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:46:57,202][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:46:57,202][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:47:13,056][onir_pt][DEBUG] [finished] batches: [15.85s] [6250it] [394.25it/s]
[2026-03-29 09:47:13,149][onir_pt][DEBUG] [finished] validation [15.95s]
[2026-03-29 09:47:13,149][onir_pt][INFO] validation it=65 map=0.2070 ndcg=0.2929 P_10=0.0636
[2026-03-29 09:47:13,150][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:47:13,150][onir_pt][DEBUG] [starting] training
[2026-03-29 09:47:13,150][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [9ms<?, ?it/s]

[2026-03-29 09:47:18,764][onir_pt][DEBUG] [finished] train pairs: [5.61s] [1024it] [182.40it/s]
[2026-03-29 09:47:18,767][onir_pt][DEBUG] [finished] training [5.62s]
[2026-03-29 09:47:18,768][onir_pt][INFO] training   it=66 loss=0.1105
[2026-03-29 09:47:18,768][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:47:18,768][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:47:18,769][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [14ms<?, ?it/s]

[2026-03-29 09:47:34,110][onir_pt][DEBUG] [finished] batches: [15.34s] [6250it] [407.43it/s]
[2026-03-29 09:47:34,197][onir_pt][DEBUG] [finished] validation [15.43s]
[2026-03-29 09:47:34,197][onir_pt][INFO] validation it=66 map=0.1964 ndcg=0.2840 P_10=0.0622
[2026-03-29 09:47:34,197][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:47:34,198][onir_pt][DEBUG] [starting] training
[2026-03-29 09:47:34,198][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:47:39,928][onir_pt][DEBUG] [finished] train pairs: [5.73s] [1024it] [178.70it/s]
[2026-03-29 09:47:39,931][onir_pt][DEBUG] [finished] training [5.73s]
[2026-03-29 09:47:39,932][onir_pt][INFO] training   it=67 loss=0.1125
[2026-03-29 09:47:39,932][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:47:39,933][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:47:39,933][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:47:56,332][onir_pt][DEBUG] [finished] batches: [16.40s] [6250it] [381.12it/s]
[2026-03-29 09:47:56,421][onir_pt][DEBUG] [finished] validation [16.49s]
[2026-03-29 09:47:56,421][onir_pt][INFO] validation it=67 map=0.1769 ndcg=0.2674 P_10=0.0598
[2026-03-29 09:47:56,421][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:47:56,422][onir_pt][DEBUG] [starting] training
[2026-03-29 09:47:56,422][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:48:02,205][onir_pt][DEBUG] [finished] train pairs: [5.78s] [1024it] [177.08it/s]
[2026-03-29 09:48:02,208][onir_pt][DEBUG] [finished] training [5.79s]
[2026-03-29 09:48:02,208][onir_pt][INFO] training   it=68 loss=0.1104
[2026-03-29 09:48:02,208][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:48:02,208][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:48:02,209][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:48:17,849][onir_pt][DEBUG] [finished] batches: [15.64s] [6250it] [399.64it/s]
[2026-03-29 09:48:17,985][onir_pt][DEBUG] [finished] validation [15.78s]
[2026-03-29 09:48:17,986][onir_pt][INFO] validation it=68 map=0.2064 ndcg=0.2925 P_10=0.0634
[2026-03-29 09:48:17,986][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:48:17,987][onir_pt][DEBUG] [starting] training
[2026-03-29 09:48:17,987][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:48:24,183][onir_pt][DEBUG] [finished] train pairs: [6.20s] [1024it] [165.28it/s]
[2026-03-29 09:48:24,185][onir_pt][DEBUG] [finished] training [6.20s]
[2026-03-29 09:48:24,186][onir_pt][INFO] training   it=69 loss=0.1069
[2026-03-29 09:48:24,186][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:48:24,186][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:48:24,186][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:48:39,721][onir_pt][DEBUG] [finished] batches: [15.53s] [6250it] [402.33it/s]
[2026-03-29 09:48:39,806][onir_pt][DEBUG] [finished] validation [15.62s]
[2026-03-29 09:48:39,807][onir_pt][INFO] validation it=69 map=0.2072 ndcg=0.2932 P_10=0.0630
[2026-03-29 09:48:39,807][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:48:39,807][onir_pt][DEBUG] [starting] training
[2026-03-29 09:48:39,807][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:48:45,568][onir_pt][DEBUG] [finished] train pairs: [5.76s] [1024it] [177.77it/s]
[2026-03-29 09:48:45,571][onir_pt][DEBUG] [finished] training [5.76s]
[2026-03-29 09:48:45,571][onir_pt][INFO] training   it=70 loss=0.1181
[2026-03-29 09:48:45,572][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:48:45,572][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:48:45,572][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:49:02,059][onir_pt][DEBUG] [finished] batches: [16.49s] [6250it] [379.11it/s]
[2026-03-29 09:49:02,150][onir_pt][DEBUG] [finished] validation [16.58s]
[2026-03-29 09:49:02,151][onir_pt][INFO] validation it=70 map=0.2044 ndcg=0.2907 P_10=0.0626
[2026-03-29 09:49:02,151][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:49:02,151][onir_pt][DEBUG] [starting] training
[2026-03-29 09:49:02,151][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:49:07,864][onir_pt][DEBUG] [finished] train pairs: [5.71s] [1024it] [179.27it/s]
[2026-03-29 09:49:07,868][onir_pt][DEBUG] [finished] training [5.72s]
[2026-03-29 09:49:07,868][onir_pt][INFO] training   it=71 loss=0.1167
[2026-03-29 09:49:07,869][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:49:07,869][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:49:07,870][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:49:23,500][onir_pt][DEBUG] [finished] batches: [15.63s] [6250it] [399.88it/s]
[2026-03-29 09:49:23,590][onir_pt][DEBUG] [finished] validation [15.72s]
[2026-03-29 09:49:23,591][onir_pt][INFO] validation it=71 map=0.2080 ndcg=0.2937 P_10=0.0632
[2026-03-29 09:49:23,591][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:49:23,591][onir_pt][DEBUG] [starting] training
[2026-03-29 09:49:23,592][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:49:29,838][onir_pt][DEBUG] [finished] train pairs: [6.25s] [1024it] [163.94it/s]
[2026-03-29 09:49:29,841][onir_pt][DEBUG] [finished] training [6.25s]
[2026-03-29 09:49:29,842][onir_pt][INFO] training   it=72 loss=0.1165
[2026-03-29 09:49:29,842][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:49:29,842][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:49:29,842][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:49:46,224][onir_pt][DEBUG] [finished] batches: [16.38s] [6250it] [381.54it/s]
[2026-03-29 09:49:46,323][onir_pt][DEBUG] [finished] validation [16.48s]
[2026-03-29 09:49:46,323][onir_pt][INFO] validation it=72 map=0.2058 ndcg=0.2917 P_10=0.0634
[2026-03-29 09:49:46,324][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:49:46,324][onir_pt][DEBUG] [starting] training
[2026-03-29 09:49:46,324][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:49:52,192][onir_pt][DEBUG] [finished] train pairs: [5.87s] [1024it] [174.52it/s]
[2026-03-29 09:49:52,193][onir_pt][DEBUG] [finished] training [5.87s]
[2026-03-29 09:49:52,194][onir_pt][INFO] training   it=73 loss=0.1098
[2026-03-29 09:49:52,195][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:49:52,195][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:49:52,195][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:50:09,358][onir_pt][DEBUG] [finished] batches: [17.16s] [6250it] [364.18it/s]
[2026-03-29 09:50:09,502][onir_pt][DEBUG] [finished] validation [17.31s]
[2026-03-29 09:50:09,502][onir_pt][INFO] validation it=73 map=0.2035 ndcg=0.2904 P_10=0.0648
[2026-03-29 09:50:09,503][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:50:09,503][onir_pt][DEBUG] [starting] training
[2026-03-29 09:50:09,503][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:50:15,622][onir_pt][DEBUG] [finished] train pairs: [6.12s] [1024it] [167.36it/s]
[2026-03-29 09:50:15,625][onir_pt][DEBUG] [finished] training [6.12s]
[2026-03-29 09:50:15,625][onir_pt][INFO] training   it=74 loss=0.1254
[2026-03-29 09:50:15,625][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:50:15,625][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:50:15,626][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:50:31,862][onir_pt][DEBUG] [finished] batches: [16.24s] [6250it] [384.95it/s]
[2026-03-29 09:50:31,949][onir_pt][DEBUG] [finished] validation [16.32s]
[2026-03-29 09:50:31,950][onir_pt][INFO] validation it=74 map=0.2085 ndcg=0.2938 P_10=0.0660
[2026-03-29 09:50:31,950][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:50:31,950][onir_pt][DEBUG] [starting] training
[2026-03-29 09:50:31,950][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:50:38,233][onir_pt][DEBUG] [finished] train pairs: [6.28s] [1024it] [162.99it/s]
[2026-03-29 09:50:38,235][onir_pt][DEBUG] [finished] training [6.28s]
[2026-03-29 09:50:38,235][onir_pt][INFO] training   it=75 loss=0.1138
[2026-03-29 09:50:38,235][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:50:38,235][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:50:38,236][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:50:55,081][onir_pt][DEBUG] [finished] batches: [16.84s] [6250it] [371.04it/s]
[2026-03-29 09:50:55,167][onir_pt][DEBUG] [finished] validation [16.93s]
[2026-03-29 09:50:55,168][onir_pt][INFO] validation it=75 map=0.2074 ndcg=0.2927 P_10=0.0638
[2026-03-29 09:50:55,168][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:50:55,168][onir_pt][DEBUG] [starting] training
[2026-03-29 09:50:55,168][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [7ms<?, ?it/s]

[2026-03-29 09:51:01,068][onir_pt][DEBUG] [finished] train pairs: [5.90s] [1024it] [173.57it/s]
[2026-03-29 09:51:01,071][onir_pt][DEBUG] [finished] training [5.90s]
[2026-03-29 09:51:01,071][onir_pt][INFO] training   it=76 loss=0.1157
[2026-03-29 09:51:01,071][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:51:01,072][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:51:01,072][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:51:17,543][onir_pt][DEBUG] [finished] batches: [16.47s] [6250it] [379.46it/s]
[2026-03-29 09:51:17,691][onir_pt][DEBUG] [finished] validation [16.62s]
[2026-03-29 09:51:17,692][onir_pt][INFO] validation it=76 map=0.1930 ndcg=0.2813 P_10=0.0628
[2026-03-29 09:51:17,692][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:51:17,692][onir_pt][DEBUG] [starting] training
[2026-03-29 09:51:17,692][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:51:23,588][onir_pt][DEBUG] [finished] train pairs: [5.90s] [1024it] [173.70it/s]
[2026-03-29 09:51:23,590][onir_pt][DEBUG] [finished] training [5.90s]
[2026-03-29 09:51:23,590][onir_pt][INFO] training   it=77 loss=0.1195
[2026-03-29 09:51:23,591][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:51:23,591][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:51:23,591][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:51:40,036][onir_pt][DEBUG] [finished] batches: [16.44s] [6250it] [380.06it/s]
[2026-03-29 09:51:40,142][onir_pt][DEBUG] [finished] validation [16.55s]
[2026-03-29 09:51:40,143][onir_pt][INFO] validation it=77 map=0.1928 ndcg=0.2810 P_10=0.0624
[2026-03-29 09:51:40,143][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:51:40,143][onir_pt][DEBUG] [starting] training
[2026-03-29 09:51:40,144][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:51:46,342][onir_pt][DEBUG] [finished] train pairs: [6.20s] [1024it] [165.22it/s]
[2026-03-29 09:51:46,344][onir_pt][DEBUG] [finished] training [6.20s]
[2026-03-29 09:51:46,345][onir_pt][INFO] training   it=78 loss=0.1171
[2026-03-29 09:51:46,345][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:51:46,345][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:51:46,345][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [16ms<?, ?it/s]

[2026-03-29 09:52:03,258][onir_pt][DEBUG] [finished] batches: [16.91s] [6250it] [369.54it/s]
[2026-03-29 09:52:03,350][onir_pt][DEBUG] [finished] validation [17.01s]
[2026-03-29 09:52:03,351][onir_pt][INFO] validation it=78 map=0.2031 ndcg=0.2900 P_10=0.0630
[2026-03-29 09:52:03,351][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:52:03,351][onir_pt][DEBUG] [starting] training
[2026-03-29 09:52:03,351][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:52:09,239][onir_pt][DEBUG] [finished] train pairs: [5.89s] [1024it] [173.92it/s]
[2026-03-29 09:52:09,243][onir_pt][DEBUG] [finished] training [5.89s]
[2026-03-29 09:52:09,244][onir_pt][INFO] training   it=79 loss=0.1160
[2026-03-29 09:52:09,244][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:52:09,244][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:52:09,245][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [14ms<?, ?it/s]

[2026-03-29 09:52:25,427][onir_pt][DEBUG] [finished] batches: [16.18s] [6250it] [386.25it/s]
[2026-03-29 09:52:25,518][onir_pt][DEBUG] [finished] validation [16.27s]
[2026-03-29 09:52:25,519][onir_pt][INFO] validation it=79 map=0.2084 ndcg=0.2942 P_10=0.0650
[2026-03-29 09:52:25,519][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:52:25,519][onir_pt][DEBUG] [starting] training
[2026-03-29 09:52:25,520][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:52:32,017][onir_pt][DEBUG] [finished] train pairs: [6.50s] [1024it] [157.60it/s]
[2026-03-29 09:52:32,020][onir_pt][DEBUG] [finished] training [6.50s]
[2026-03-29 09:52:32,020][onir_pt][INFO] training   it=80 loss=0.1121
[2026-03-29 09:52:32,021][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:52:32,021][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:52:32,021][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [13ms<?, ?it/s]

[2026-03-29 09:52:48,547][onir_pt][DEBUG] [finished] batches: [16.52s] [6250it] [378.22it/s]
[2026-03-29 09:52:48,654][onir_pt][DEBUG] [finished] validation [16.63s]
[2026-03-29 09:52:48,654][onir_pt][INFO] validation it=80 map=0.1849 ndcg=0.2741 P_10=0.0614
[2026-03-29 09:52:48,654][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:52:48,655][onir_pt][DEBUG] [starting] training
[2026-03-29 09:52:48,655][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:52:54,381][onir_pt][DEBUG] [finished] train pairs: [5.73s] [1024it] [178.84it/s]
[2026-03-29 09:52:54,382][onir_pt][DEBUG] [finished] training [5.73s]
[2026-03-29 09:52:54,382][onir_pt][INFO] training   it=81 loss=0.1153
[2026-03-29 09:52:54,383][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:52:54,383][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:52:54,384][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:53:11,234][onir_pt][DEBUG] [finished] batches: [16.85s] [6250it] [370.92it/s]
[2026-03-29 09:53:11,388][onir_pt][DEBUG] [finished] validation [17.01s]
[2026-03-29 09:53:11,389][onir_pt][INFO] validation it=81 map=0.2067 ndcg=0.2928 P_10=0.0644
[2026-03-29 09:53:11,389][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:53:11,389][onir_pt][DEBUG] [starting] training
[2026-03-29 09:53:11,389][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [12ms<?, ?it/s]

[2026-03-29 09:53:17,299][onir_pt][DEBUG] [finished] train pairs: [5.91s] [1024it] [173.28it/s]
[2026-03-29 09:53:17,301][onir_pt][DEBUG] [finished] training [5.91s]
[2026-03-29 09:53:17,302][onir_pt][INFO] training   it=82 loss=0.1194
[2026-03-29 09:53:17,302][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:53:17,302][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:53:17,303][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:53:33,405][onir_pt][DEBUG] [finished] batches: [16.10s] [6250it] [388.15it/s]
[2026-03-29 09:53:33,493][onir_pt][DEBUG] [finished] validation [16.19s]
[2026-03-29 09:53:33,493][onir_pt][INFO] validation it=82 map=0.2067 ndcg=0.2927 P_10=0.0634
[2026-03-29 09:53:33,493][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:53:33,494][onir_pt][DEBUG] [starting] training
[2026-03-29 09:53:33,494][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:53:39,716][onir_pt][DEBUG] [finished] train pairs: [6.22s] [1024it] [164.58it/s]
[2026-03-29 09:53:39,717][onir_pt][DEBUG] [finished] training [6.22s]
[2026-03-29 09:53:39,718][onir_pt][INFO] training   it=83 loss=0.1072
[2026-03-29 09:53:39,718][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:53:39,720][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:53:39,721][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:53:56,293][onir_pt][DEBUG] [finished] batches: [16.57s] [6250it] [377.14it/s]
[2026-03-29 09:53:56,384][onir_pt][DEBUG] [finished] validation [16.67s]
[2026-03-29 09:53:56,386][onir_pt][INFO] validation it=83 map=0.2128 ndcg=0.2981 P_10=0.0650 <--
[2026-03-29 09:53:56,386][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:53:56,387][onir_pt][DEBUG] [starting] training
[2026-03-29 09:53:56,387][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:54:01,961][onir_pt][DEBUG] [finished] train pairs: [5.57s] [1024it] [183.72it/s]
[2026-03-29 09:54:01,962][onir_pt][DEBUG] [finished] training [5.58s]
[2026-03-29 09:54:01,964][onir_pt][INFO] training   it=84 loss=0.1042
[2026-03-29 09:54:01,964][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:54:01,964][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:54:01,966][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:54:18,483][onir_pt][DEBUG] [finished] batches: [16.52s] [6250it] [378.41it/s]
[2026-03-29 09:54:18,586][onir_pt][DEBUG] [finished] validation [16.62s]
[2026-03-29 09:54:18,586][onir_pt][INFO] validation it=84 map=0.2100 ndcg=0.2956 P_10=0.0650
[2026-03-29 09:54:18,587][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:54:18,587][onir_pt][DEBUG] [starting] training
[2026-03-29 09:54:18,587][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:54:25,226][onir_pt][DEBUG] [finished] train pairs: [6.64s] [1024it] [154.26it/s]
[2026-03-29 09:54:25,228][onir_pt][DEBUG] [finished] training [6.64s]
[2026-03-29 09:54:25,228][onir_pt][INFO] training   it=85 loss=0.1207
[2026-03-29 09:54:25,228][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:54:25,228][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:54:25,229][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:54:41,386][onir_pt][DEBUG] [finished] batches: [16.16s] [6250it] [386.83it/s]
[2026-03-29 09:54:41,476][onir_pt][DEBUG] [finished] validation [16.25s]
[2026-03-29 09:54:41,477][onir_pt][INFO] validation it=85 map=0.2002 ndcg=0.2872 P_10=0.0638
[2026-03-29 09:54:41,477][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:54:41,477][onir_pt][DEBUG] [starting] training
[2026-03-29 09:54:41,478][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:54:47,042][onir_pt][DEBUG] [finished] train pairs: [5.56s] [1024it] [184.02it/s]
[2026-03-29 09:54:47,046][onir_pt][DEBUG] [finished] training [5.57s]
[2026-03-29 09:54:47,046][onir_pt][INFO] training   it=86 loss=0.1173
[2026-03-29 09:54:47,047][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:54:47,047][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:54:47,047][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:55:03,464][onir_pt][DEBUG] [finished] batches: [16.42s] [6250it] [380.73it/s]
[2026-03-29 09:55:03,615][onir_pt][DEBUG] [finished] validation [16.57s]
[2026-03-29 09:55:03,616][onir_pt][INFO] validation it=86 map=0.2010 ndcg=0.2878 P_10=0.0630
[2026-03-29 09:55:03,616][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:55:03,616][onir_pt][DEBUG] [starting] training
[2026-03-29 09:55:03,616][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [14ms<?, ?it/s]

[2026-03-29 09:55:09,612][onir_pt][DEBUG] [finished] train pairs: [5.99s] [1024it] [170.81it/s]
[2026-03-29 09:55:09,613][onir_pt][DEBUG] [finished] training [6.00s]
[2026-03-29 09:55:09,614][onir_pt][INFO] training   it=87 loss=0.1147
[2026-03-29 09:55:09,614][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:55:09,614][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:55:09,614][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 09:55:25,682][onir_pt][DEBUG] [finished] batches: [16.07s] [6250it] [388.98it/s]
[2026-03-29 09:55:25,772][onir_pt][DEBUG] [finished] validation [16.16s]
[2026-03-29 09:55:25,772][onir_pt][INFO] validation it=87 map=0.1935 ndcg=0.2813 P_10=0.0616
[2026-03-29 09:55:25,772][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:55:25,773][onir_pt][DEBUG] [starting] training
[2026-03-29 09:55:25,773][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:55:31,477][onir_pt][DEBUG] [finished] train pairs: [5.70s] [1024it] [179.54it/s]
[2026-03-29 09:55:31,479][onir_pt][DEBUG] [finished] training [5.71s]
[2026-03-29 09:55:31,479][onir_pt][INFO] training   it=88 loss=0.1081
[2026-03-29 09:55:31,479][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:55:31,479][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:55:31,480][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:55:48,562][onir_pt][DEBUG] [finished] batches: [17.08s] [6250it] [365.90it/s]
[2026-03-29 09:55:48,653][onir_pt][DEBUG] [finished] validation [17.17s]
[2026-03-29 09:55:48,653][onir_pt][INFO] validation it=88 map=0.2080 ndcg=0.2936 P_10=0.0630
[2026-03-29 09:55:48,653][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:55:48,654][onir_pt][DEBUG] [starting] training
[2026-03-29 09:55:48,654][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:55:54,262][onir_pt][DEBUG] [finished] train pairs: [5.61s] [1024it] [182.59it/s]
[2026-03-29 09:55:54,265][onir_pt][DEBUG] [finished] training [5.61s]
[2026-03-29 09:55:54,265][onir_pt][INFO] training   it=89 loss=0.1149
[2026-03-29 09:55:54,265][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:55:54,265][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:55:54,266][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:56:10,474][onir_pt][DEBUG] [finished] batches: [16.21s] [6250it] [385.62it/s]
[2026-03-29 09:56:10,562][onir_pt][DEBUG] [finished] validation [16.30s]
[2026-03-29 09:56:10,563][onir_pt][INFO] validation it=89 map=0.2067 ndcg=0.2922 P_10=0.0634
[2026-03-29 09:56:10,563][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:56:10,563][onir_pt][DEBUG] [starting] training
[2026-03-29 09:56:10,564][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:56:17,039][onir_pt][DEBUG] [finished] train pairs: [6.48s] [1024it] [158.14it/s]
[2026-03-29 09:56:17,041][onir_pt][DEBUG] [finished] training [6.48s]
[2026-03-29 09:56:17,042][onir_pt][INFO] training   it=90 loss=0.1134
[2026-03-29 09:56:17,042][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:56:17,042][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:56:17,043][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:56:33,212][onir_pt][DEBUG] [finished] batches: [16.17s] [6250it] [386.54it/s]
[2026-03-29 09:56:33,304][onir_pt][DEBUG] [finished] validation [16.26s]
[2026-03-29 09:56:33,305][onir_pt][INFO] validation it=90 map=0.2036 ndcg=0.2903 P_10=0.0624
[2026-03-29 09:56:33,305][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:56:33,305][onir_pt][DEBUG] [starting] training
[2026-03-29 09:56:33,305][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:56:39,253][onir_pt][DEBUG] [finished] train pairs: [5.95s] [1024it] [172.18it/s]
[2026-03-29 09:56:39,256][onir_pt][DEBUG] [finished] training [5.95s]
[2026-03-29 09:56:39,258][onir_pt][INFO] training   it=91 loss=0.1042
[2026-03-29 09:56:39,258][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:56:39,258][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:56:39,259][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:56:55,958][onir_pt][DEBUG] [finished] batches: [16.70s] [6250it] [374.28it/s]
[2026-03-29 09:56:56,056][onir_pt][DEBUG] [finished] validation [16.80s]
[2026-03-29 09:56:56,057][onir_pt][INFO] validation it=91 map=0.1963 ndcg=0.2840 P_10=0.0626
[2026-03-29 09:56:56,057][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:56:56,057][onir_pt][DEBUG] [starting] training
[2026-03-29 09:56:56,057][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 09:57:01,658][onir_pt][DEBUG] [finished] train pairs: [5.60s] [1024it] [182.85it/s]
[2026-03-29 09:57:01,659][onir_pt][DEBUG] [finished] training [5.60s]
[2026-03-29 09:57:01,660][onir_pt][INFO] training   it=92 loss=0.1073
[2026-03-29 09:57:01,660][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:57:01,660][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:57:01,663][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:57:17,691][onir_pt][DEBUG] [finished] batches: [16.03s] [6250it] [389.96it/s]
[2026-03-29 09:57:17,778][onir_pt][DEBUG] [finished] validation [16.12s]
[2026-03-29 09:57:17,779][onir_pt][INFO] validation it=92 map=0.2031 ndcg=0.2898 P_10=0.0630
[2026-03-29 09:57:17,779][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:57:17,779][onir_pt][DEBUG] [starting] training
[2026-03-29 09:57:17,779][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:57:24,109][onir_pt][DEBUG] [finished] train pairs: [6.33s] [1024it] [161.80it/s]
[2026-03-29 09:57:24,110][onir_pt][DEBUG] [finished] training [6.33s]
[2026-03-29 09:57:24,111][onir_pt][INFO] training   it=93 loss=0.1148
[2026-03-29 09:57:24,111][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:57:24,111][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:57:24,111][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [16ms<?, ?it/s]

[2026-03-29 09:57:40,712][onir_pt][DEBUG] [finished] batches: [16.60s] [6250it] [376.51it/s]
[2026-03-29 09:57:40,806][onir_pt][DEBUG] [finished] validation [16.70s]
[2026-03-29 09:57:40,807][onir_pt][INFO] validation it=93 map=0.2044 ndcg=0.2909 P_10=0.0626
[2026-03-29 09:57:40,807][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:57:40,807][onir_pt][DEBUG] [starting] training
[2026-03-29 09:57:40,808][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:57:46,302][onir_pt][DEBUG] [finished] train pairs: [5.49s] [1024it] [186.40it/s]
[2026-03-29 09:57:46,303][onir_pt][DEBUG] [finished] training [5.50s]
[2026-03-29 09:57:46,304][onir_pt][INFO] training   it=94 loss=0.1066
[2026-03-29 09:57:46,304][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:57:46,304][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:57:46,304][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 09:58:02,798][onir_pt][DEBUG] [finished] batches: [16.49s] [6250it] [378.95it/s]
[2026-03-29 09:58:02,944][onir_pt][DEBUG] [finished] validation [16.64s]
[2026-03-29 09:58:02,944][onir_pt][INFO] validation it=94 map=0.2062 ndcg=0.2922 P_10=0.0640
[2026-03-29 09:58:02,945][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:58:02,945][onir_pt][DEBUG] [starting] training
[2026-03-29 09:58:02,945][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [15ms<?, ?it/s]

[2026-03-29 09:58:09,248][onir_pt][DEBUG] [finished] train pairs: [6.30s] [1024it] [162.48it/s]
[2026-03-29 09:58:09,250][onir_pt][DEBUG] [finished] training [6.31s]
[2026-03-29 09:58:09,251][onir_pt][INFO] training   it=95 loss=0.1121
[2026-03-29 09:58:09,251][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:58:09,251][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:58:09,252][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:58:25,655][onir_pt][DEBUG] [finished] batches: [16.40s] [6250it] [381.02it/s]
[2026-03-29 09:58:25,749][onir_pt][DEBUG] [finished] validation [16.50s]
[2026-03-29 09:58:25,750][onir_pt][INFO] validation it=95 map=0.2018 ndcg=0.2880 P_10=0.0626
[2026-03-29 09:58:25,750][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:58:25,750][onir_pt][DEBUG] [starting] training
[2026-03-29 09:58:25,750][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:58:31,873][onir_pt][DEBUG] [finished] train pairs: [6.12s] [1024it] [167.26it/s]
[2026-03-29 09:58:31,876][onir_pt][DEBUG] [finished] training [6.13s]
[2026-03-29 09:58:31,876][onir_pt][INFO] training   it=96 loss=0.1169
[2026-03-29 09:58:31,876][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:58:31,877][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:58:31,877][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:58:48,653][onir_pt][DEBUG] [finished] batches: [16.77s] [6250it] [372.58it/s]
[2026-03-29 09:58:48,744][onir_pt][DEBUG] [finished] validation [16.87s]
[2026-03-29 09:58:48,745][onir_pt][INFO] validation it=96 map=0.1999 ndcg=0.2867 P_10=0.0626
[2026-03-29 09:58:48,745][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:58:48,745][onir_pt][DEBUG] [starting] training
[2026-03-29 09:58:48,745][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:58:54,272][onir_pt][DEBUG] [finished] train pairs: [5.53s] [1024it] [185.29it/s]
[2026-03-29 09:58:54,274][onir_pt][DEBUG] [finished] training [5.53s]
[2026-03-29 09:58:54,275][onir_pt][INFO] training   it=97 loss=0.1095
[2026-03-29 09:58:54,275][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:58:54,275][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:58:54,276][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [11ms<?, ?it/s]

[2026-03-29 09:59:10,665][onir_pt][DEBUG] [finished] batches: [16.39s] [6250it] [381.34it/s]
[2026-03-29 09:59:10,774][onir_pt][DEBUG] [finished] validation [16.50s]
[2026-03-29 09:59:10,775][onir_pt][INFO] validation it=97 map=0.2071 ndcg=0.2928 P_10=0.0638
[2026-03-29 09:59:10,775][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:59:10,775][onir_pt][DEBUG] [starting] training
[2026-03-29 09:59:10,775][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:59:16,973][onir_pt][DEBUG] [finished] train pairs: [6.20s] [1024it] [165.22it/s]
[2026-03-29 09:59:16,975][onir_pt][DEBUG] [finished] training [6.20s]
[2026-03-29 09:59:16,976][onir_pt][INFO] training   it=98 loss=0.1079
[2026-03-29 09:59:16,977][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:59:16,977][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:59:16,977][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [18ms<?, ?it/s]

[2026-03-29 09:59:33,731][onir_pt][DEBUG] [finished] batches: [16.75s] [6250it] [373.06it/s]
[2026-03-29 09:59:33,823][onir_pt][DEBUG] [finished] validation [16.85s]
[2026-03-29 09:59:33,823][onir_pt][INFO] validation it=98 map=0.1982 ndcg=0.2855 P_10=0.0630
[2026-03-29 09:59:33,823][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:59:33,824][onir_pt][DEBUG] [starting] training
[2026-03-29 09:59:33,824][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 09:59:39,400][onir_pt][DEBUG] [finished] train pairs: [5.58s] [1024it] [183.64it/s]
[2026-03-29 09:59:39,403][onir_pt][DEBUG] [finished] training [5.58s]
[2026-03-29 09:59:39,403][onir_pt][INFO] training   it=99 loss=0.1076
[2026-03-29 09:59:39,403][onir_pt][DEBUG] [starting] validation
[2026-03-29 09:59:39,403][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:59:39,404][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [9ms<?, ?it/s]

[2026-03-29 09:59:55,903][onir_pt][DEBUG] [finished] batches: [16.50s] [6250it] [378.81it/s]
[2026-03-29 09:59:56,062][onir_pt][DEBUG] [finished] validation [16.66s]
[2026-03-29 09:59:56,063][onir_pt][INFO] validation it=99 map=0.1974 ndcg=0.2848 P_10=0.0626
[2026-03-29 09:59:56,063][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 09:59:56,063][onir_pt][DEBUG] [starting] training
[2026-03-29 09:59:56,063][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [10ms<?, ?it/s]

[2026-03-29 10:00:02,009][onir_pt][DEBUG] [finished] train pairs: [5.95s] [1024it] [172.24it/s]
[2026-03-29 10:00:02,011][onir_pt][DEBUG] [finished] training [5.95s]
[2026-03-29 10:00:02,012][onir_pt][INFO] training   it=100 loss=0.1163
[2026-03-29 10:00:02,012][onir_pt][DEBUG] [starting] validation
[2026-03-29 10:00:02,012][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:00:02,013][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 10:00:18,598][onir_pt][DEBUG] [finished] batches: [16.58s] [6250it] [376.86it/s]
[2026-03-29 10:00:18,705][onir_pt][DEBUG] [finished] validation [16.69s]
[2026-03-29 10:00:18,706][onir_pt][INFO] validation it=100 map=0.1927 ndcg=0.2808 P_10=0.0616
[2026-03-29 10:00:18,706][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:00:18,706][onir_pt][DEBUG] [starting] training
[2026-03-29 10:00:18,706][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [6ms<?, ?it/s]

[2026-03-29 10:00:24,332][onir_pt][DEBUG] [finished] train pairs: [5.63s] [1024it] [182.04it/s]
[2026-03-29 10:00:24,333][onir_pt][DEBUG] [finished] training [5.63s]
[2026-03-29 10:00:24,334][onir_pt][INFO] training   it=101 loss=0.1157
[2026-03-29 10:00:24,334][onir_pt][DEBUG] [starting] validation
[2026-03-29 10:00:24,334][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:00:24,335][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 10:00:41,649][onir_pt][DEBUG] [finished] batches: [17.31s] [6250it] [360.97it/s]
[2026-03-29 10:00:41,747][onir_pt][DEBUG] [finished] validation [17.41s]
[2026-03-29 10:00:41,748][onir_pt][INFO] validation it=101 map=0.2091 ndcg=0.2945 P_10=0.0632
[2026-03-29 10:00:41,748][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:00:41,748][onir_pt][DEBUG] [starting] training
[2026-03-29 10:00:41,749][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 10:00:47,206][onir_pt][DEBUG] [finished] train pairs: [5.46s] [1024it] [187.64it/s]
[2026-03-29 10:00:47,208][onir_pt][DEBUG] [finished] training [5.46s]
[2026-03-29 10:00:47,209][onir_pt][INFO] training   it=102 loss=0.1067
[2026-03-29 10:00:47,209][onir_pt][DEBUG] [starting] validation
[2026-03-29 10:00:47,209][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:00:47,209][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [10ms<?, ?it/s]

[2026-03-29 10:01:03,768][onir_pt][DEBUG] [finished] batches: [16.56s] [6250it] [377.45it/s]
[2026-03-29 10:01:03,857][onir_pt][DEBUG] [finished] validation [16.65s]
[2026-03-29 10:01:03,858][onir_pt][INFO] validation it=102 map=0.2044 ndcg=0.2903 P_10=0.0644
[2026-03-29 10:01:03,858][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:01:03,858][onir_pt][DEBUG] [starting] training
[2026-03-29 10:01:03,858][onir_pt][DEBUG] [starting] train pairs

train pairs:   0%|          | 0/1024 [5ms<?, ?it/s]

[2026-03-29 10:01:09,943][onir_pt][DEBUG] [finished] train pairs: [6.08s] [1024it] [168.30it/s]
[2026-03-29 10:01:09,944][onir_pt][DEBUG] [finished] training [6.09s]
[2026-03-29 10:01:09,946][onir_pt][INFO] training   it=103 loss=0.1118
[2026-03-29 10:01:09,946][onir_pt][DEBUG] [starting] validation
[2026-03-29 10:01:09,946][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:01:09,947][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/6250 [12ms<?, ?it/s]

[2026-03-29 10:01:26,853][onir_pt][DEBUG] [finished] batches: [16.91s] [6250it] [369.69it/s]
[2026-03-29 10:01:26,944][onir_pt][DEBUG] [finished] validation [17.00s]
[2026-03-29 10:01:26,945][onir_pt][INFO] validation it=103 map=0.2090 ndcg=0.2940 P_10=0.0636
[2026-03-29 10:01:26,945][onir_pt][INFO] early stopping; model reverting back to it=83

In [ ]:
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    test_qrels,
    names=['TFIDF', 'TFIDF >> KNRM (trained)'],
    eval_metrics=[AP(rel=1), nDCG, nDCG@10, P(rel=1)@10]
)

[2026-03-29 10:11:31,059][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:11:31,060][onir_pt][DEBUG] [starting] batches

batches: 0it [17ms, ?it/s]

[2026-03-29 10:11:31,085][onir_pt][DEBUG] [finished] batches: [24ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> KNRM (trained) ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b66662c770> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-29 10:12:10,659][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:12:10,660][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/8100 [6ms<?, ?it/s]

[2026-03-29 10:12:27,899][onir_pt][DEBUG] [finished] batches: [17.24s] [8100it] [469.88it/s]

                      name        AP      P@10      nDCG   nDCG@10
0                    TFIDF  0.197242  0.067901  0.289927  0.242948
1  TFIDF >> KNRM (trained)  0.191779  0.065432  0.285757  0.238424

Vanilla Bert

In [ ]:
del knrm # clear out memory from KNRM
vbert = onir_pt.reranker('vanilla_transformer', 'bert', text_field='text', vocab_config={'train': True})

In [ ]:
pipeline = tfidf % 50 >> get_text >> vbert
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    test_qrels,
    names=['TFIDF', 'TFIDF >> VBERT'],
    baseline=0,
    eval_metrics=[AP(rel=1), nDCG, nDCG@10, P(rel=1)@10]
)

[2026-03-29 10:13:05,405][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:13:05,558][onir_pt][DEBUG] [starting] batches

batches: 0it [6ms, ?it/s]

[2026-03-29 10:13:05,575][onir_pt][DEBUG] [finished] batches: [16ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> VBERT ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x79b66662c770> >> onir(vanilla_transformer,bert)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-29 10:13:39,839][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-29 10:13:39,843][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/8100 [5ms<?, ?it/s]

[2026-03-29 10:34:42,702][onir_pt][DEBUG] [finished] batches: [21:03] [8100it] [ 6.41it/s]

,name,AP,P@10,nDCG,nDCG@10,AP +,AP -,AP p-value,P@10 +,P@10 -,P@10 p-value,nDCG +,nDCG -,nDCG p-value,nDCG@10 +,nDCG@10 -,nDCG@10 p-value
0,TFIDF,0.197242,0.067901,0.289927,0.242948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TFIDF >> VBERT,0.028694,0.010185,0.128566,0.021958,62.0,372.0,7.765113e-46,22.0,282.0,2.408661e-49,62.0,372.0,1.403861e-53,23.0,306.0,8.552556e-56

Mono T5

In [ ]:
monoT5 = MonoT5ReRanker(text_field='text')

In [ ]:
pipeline = (tfidf >> get_text >> monoT5)
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    test_qrels,
    names=['TFIDF', 'TFIDF >> T5'],
    eval_metrics=[AP(rel=1), nDCG, nDCG@10, P(rel=1)@10, "mrt"]
)

monoT5:   0%|          | 0/8100 [6ms<?, ?batches/s]

          name        AP      P@10      nDCG   nDCG@10           mrt
0        TFIDF  0.197242  0.067901  0.289927  0.242948  1.828712e+04
1  TFIDF >> T5  0.300543  0.092593  0.380061  0.362656  1.234975e+06

#### Question ✍
Do you see any advantages compared to Learning to Rank?

Neural Learning Models such as Bert and monoT5 have best performances than TFIDF. We see that Bert surpases TF-IDF by 0.1. This outperferformance goes at the cost of inference and training time. This PW used a total of 11.7 GB of RAM, 6 GB Of GPU and 49.4 GB of disk using the T4 GPU provided by Google Collab. Neuronal Network are more precise at the cost of ressources and compute time.